package theme.scheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import theme.color.Android

val AndroidLight = lightColorScheme(
    primary = Android.PrimaryLight,
    onPrimary = Android.OnPrimaryLight,
    primaryContainer = Android.PrimaryContainerLight,
    onPrimaryContainer = Android.OnPrimaryContainerLight,
    secondary = Android.SecondaryLight,
    onSecondary = Android.OnSecondaryLight,
    secondaryContainer = Android.SecondaryContainerLight,
    onSecondaryContainer = Android.OnSecondaryContainerLight,
    tertiary = Android.TertiaryLight,
    onTertiary = Android.OnTertiaryLight,
    tertiaryContainer = Android.TertiaryContainerLight,
    onTertiaryContainer = Android.OnTertiaryContainerLight,
    error = Android.ErrorLight,
    onError = Android.OnErrorLight,
    errorContainer = Android.ErrorContainerLight,
    onErrorContainer = Android.OnErrorContainerLight,
    background = Android.BackgroundLight,
    onBackground = Android.OnBackgroundLight,
    surface = Android.SurfaceLight,
    onSurface = Android.OnSurfaceLight,
    surfaceVariant = Android.SurfaceVariantLight,
    onSurfaceVariant = Android.OnSurfaceVariantLight,
    outline = Android.OutlineLight,
    outlineVariant = Android.OutlineVariantLight,
    scrim = Android.ScrimLight,
    inverseSurface = Android.InverseSurfaceLight,
    inverseOnSurface = Android.InverseOnSurfaceLight,
    inversePrimary = Android.InversePrimaryLight,
    surfaceDim = Android.SurfaceDimLight,
    surfaceBright = Android.SurfaceBrightLight,
    surfaceContainerLowest = Android.SurfaceContainerLowestLight,
    surfaceContainerLow = Android.SurfaceContainerLowLight,
    surfaceContainer = Android.SurfaceContainerLight,
    surfaceContainerHigh = Android.SurfaceContainerHighLight,
    surfaceContainerHighest = Android.SurfaceContainerHighestLight,
)

val AndroidDark = darkColorScheme(
    primary = Android.PrimaryDark,
    onPrimary = Android.OnPrimaryDark,
    primaryContainer = Android.PrimaryContainerDark,
    onPrimaryContainer = Android.OnPrimaryContainerDark,
    secondary = Android.SecondaryDark,
    onSecondary = Android.OnSecondaryDark,
    secondaryContainer = Android.SecondaryContainerDark,
    onSecondaryContainer = Android.OnSecondaryContainerDark,
    tertiary = Android.TertiaryDark,
    onTertiary = Android.OnTertiaryDark,
    tertiaryContainer = Android.TertiaryContainerDark,
    onTertiaryContainer = Android.OnTertiaryContainerDark,
    error = Android.ErrorDark,
    onError = Android.OnErrorDark,
    errorContainer = Android.ErrorContainerDark,
    onErrorContainer = Android.OnErrorContainerDark,
    background = Android.BackgroundDark,
    onBackground = Android.OnBackgroundDark,
    surface = Android.SurfaceDark,
    onSurface = Android.OnSurfaceDark,
    surfaceVariant = Android.SurfaceVariantDark,
    onSurfaceVariant = Android.OnSurfaceVariantDark,
    outline = Android.OutlineDark,
    outlineVariant = Android.OutlineVariantDark,
    scrim = Android.ScrimDark,
    inverseSurface = Android.InverseSurfaceDark,
    inverseOnSurface = Android.InverseOnSurfaceDark,
    inversePrimary = Android.InversePrimaryDark,
    surfaceDim = Android.SurfaceDimDark,
    surfaceBright = Android.SurfaceBrightDark,
    surfaceContainerLowest = Android.SurfaceContainerLowestDark,
    surfaceContainerLow = Android.SurfaceContainerLowDark,
    surfaceContainer = Android.SurfaceContainerDark,
    surfaceContainerHigh = Android.SurfaceContainerHighDark,
    surfaceContainerHighest = Android.SurfaceContainerHighestDark,
)
