package theme.scheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import theme.color.Haruki

val HarukiLight = lightColorScheme(
    primary = Haruki.PrimaryLight,
    onPrimary = Haruki.OnPrimaryLight,
    primaryContainer = Haruki.PrimaryContainerLight,
    onPrimaryContainer = Haruki.OnPrimaryContainerLight,
    secondary = Haruki.SecondaryLight,
    onSecondary = Haruki.OnSecondaryLight,
    secondaryContainer = Haruki.SecondaryContainerLight,
    onSecondaryContainer = Haruki.OnSecondaryContainerLight,
    tertiary = Haruki.TertiaryLight,
    onTertiary = Haruki.OnTertiaryLight,
    tertiaryContainer = Haruki.TertiaryContainerLight,
    onTertiaryContainer = Haruki.OnTertiaryContainerLight,
    error = Haruki.ErrorLight,
    onError = Haruki.OnErrorLight,
    errorContainer = Haruki.ErrorContainerLight,
    onErrorContainer = Haruki.OnErrorContainerLight,
    background = Haruki.BackgroundLight,
    onBackground = Haruki.OnBackgroundLight,
    surface = Haruki.SurfaceLight,
    onSurface = Haruki.OnSurfaceLight,
    surfaceVariant = Haruki.SurfaceVariantLight,
    onSurfaceVariant = Haruki.OnSurfaceVariantLight,
    outline = Haruki.OutlineLight,
    outlineVariant = Haruki.OutlineVariantLight,
    scrim = Haruki.ScrimLight,
    inverseSurface = Haruki.InverseSurfaceLight,
    inverseOnSurface = Haruki.InverseOnSurfaceLight,
    inversePrimary = Haruki.InversePrimaryLight,
    surfaceDim = Haruki.SurfaceDimLight,
    surfaceBright = Haruki.SurfaceBrightLight,
    surfaceContainerLowest = Haruki.SurfaceContainerLowestLight,
    surfaceContainerLow = Haruki.SurfaceContainerLowLight,
    surfaceContainer = Haruki.SurfaceContainerLight,
    surfaceContainerHigh = Haruki.SurfaceContainerHighLight,
    surfaceContainerHighest = Haruki.SurfaceContainerHighestLight,
)

val HarukiDark = darkColorScheme(
    primary = Haruki.PrimaryDark,
    onPrimary = Haruki.OnPrimaryDark,
    primaryContainer = Haruki.PrimaryContainerDark,
    onPrimaryContainer = Haruki.OnPrimaryContainerDark,
    secondary = Haruki.SecondaryDark,
    onSecondary = Haruki.OnSecondaryDark,
    secondaryContainer = Haruki.SecondaryContainerDark,
    onSecondaryContainer = Haruki.OnSecondaryContainerDark,
    tertiary = Haruki.TertiaryDark,
    onTertiary = Haruki.OnTertiaryDark,
    tertiaryContainer = Haruki.TertiaryContainerDark,
    onTertiaryContainer = Haruki.OnTertiaryContainerDark,
    error = Haruki.ErrorDark,
    onError = Haruki.OnErrorDark,
    errorContainer = Haruki.ErrorContainerDark,
    onErrorContainer = Haruki.OnErrorContainerDark,
    background = Haruki.BackgroundDark,
    onBackground = Haruki.OnBackgroundDark,
    surface = Haruki.SurfaceDark,
    onSurface = Haruki.OnSurfaceDark,
    surfaceVariant = Haruki.SurfaceVariantDark,
    onSurfaceVariant = Haruki.OnSurfaceVariantDark,
    outline = Haruki.OutlineDark,
    outlineVariant = Haruki.OutlineVariantDark,
    scrim = Haruki.ScrimDark,
    inverseSurface = Haruki.InverseSurfaceDark,
    inverseOnSurface = Haruki.InverseOnSurfaceDark,
    inversePrimary = Haruki.InversePrimaryDark,
    surfaceDim = Haruki.SurfaceDimDark,
    surfaceBright = Haruki.SurfaceBrightDark,
    surfaceContainerLowest = Haruki.SurfaceContainerLowestDark,
    surfaceContainerLow = Haruki.SurfaceContainerLowDark,
    surfaceContainer = Haruki.SurfaceContainerDark,
    surfaceContainerHigh = Haruki.SurfaceContainerHighDark,
    surfaceContainerHighest = Haruki.SurfaceContainerHighestDark,
)
