package theme.scheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import theme.color.Kanade

val KanadeLight = lightColorScheme(
    primary = Kanade.PrimaryLight,
    onPrimary = Kanade.OnPrimaryLight,
    primaryContainer = Kanade.PrimaryContainerLight,
    onPrimaryContainer = Kanade.OnPrimaryContainerLight,
    secondary = Kanade.SecondaryLight,
    onSecondary = Kanade.OnSecondaryLight,
    secondaryContainer = Kanade.SecondaryContainerLight,
    onSecondaryContainer = Kanade.OnSecondaryContainerLight,
    tertiary = Kanade.TertiaryLight,
    onTertiary = Kanade.OnTertiaryLight,
    tertiaryContainer = Kanade.TertiaryContainerLight,
    onTertiaryContainer = Kanade.OnTertiaryContainerLight,
    error = Kanade.ErrorLight,
    onError = Kanade.OnErrorLight,
    errorContainer = Kanade.ErrorContainerLight,
    onErrorContainer = Kanade.OnErrorContainerLight,
    background = Kanade.BackgroundLight,
    onBackground = Kanade.OnBackgroundLight,
    surface = Kanade.SurfaceLight,
    onSurface = Kanade.OnSurfaceLight,
    surfaceVariant = Kanade.SurfaceVariantLight,
    onSurfaceVariant = Kanade.OnSurfaceVariantLight,
    outline = Kanade.OutlineLight,
    outlineVariant = Kanade.OutlineVariantLight,
    scrim = Kanade.ScrimLight,
    inverseSurface = Kanade.InverseSurfaceLight,
    inverseOnSurface = Kanade.InverseOnSurfaceLight,
    inversePrimary = Kanade.InversePrimaryLight,
    surfaceDim = Kanade.SurfaceDimLight,
    surfaceBright = Kanade.SurfaceBrightLight,
    surfaceContainerLowest = Kanade.SurfaceContainerLowestLight,
    surfaceContainerLow = Kanade.SurfaceContainerLowLight,
    surfaceContainer = Kanade.SurfaceContainerLight,
    surfaceContainerHigh = Kanade.SurfaceContainerHighLight,
    surfaceContainerHighest = Kanade.SurfaceContainerHighestLight,
)

val KanadeDark = darkColorScheme(
    primary = Kanade.PrimaryDark,
    onPrimary = Kanade.OnPrimaryDark,
    primaryContainer = Kanade.PrimaryContainerDark,
    onPrimaryContainer = Kanade.OnPrimaryContainerDark,
    secondary = Kanade.SecondaryDark,
    onSecondary = Kanade.OnSecondaryDark,
    secondaryContainer = Kanade.SecondaryContainerDark,
    onSecondaryContainer = Kanade.OnSecondaryContainerDark,
    tertiary = Kanade.TertiaryDark,
    onTertiary = Kanade.OnTertiaryDark,
    tertiaryContainer = Kanade.TertiaryContainerDark,
    onTertiaryContainer = Kanade.OnTertiaryContainerDark,
    error = Kanade.ErrorDark,
    onError = Kanade.OnErrorDark,
    errorContainer = Kanade.ErrorContainerDark,
    onErrorContainer = Kanade.OnErrorContainerDark,
    background = Kanade.BackgroundDark,
    onBackground = Kanade.OnBackgroundDark,
    surface = Kanade.SurfaceDark,
    onSurface = Kanade.OnSurfaceDark,
    surfaceVariant = Kanade.SurfaceVariantDark,
    onSurfaceVariant = Kanade.OnSurfaceVariantDark,
    outline = Kanade.OutlineDark,
    outlineVariant = Kanade.OutlineVariantDark,
    scrim = Kanade.ScrimDark,
    inverseSurface = Kanade.InverseSurfaceDark,
    inverseOnSurface = Kanade.InverseOnSurfaceDark,
    inversePrimary = Kanade.InversePrimaryDark,
    surfaceDim = Kanade.SurfaceDimDark,
    surfaceBright = Kanade.SurfaceBrightDark,
    surfaceContainerLowest = Kanade.SurfaceContainerLowestDark,
    surfaceContainerLow = Kanade.SurfaceContainerLowDark,
    surfaceContainer = Kanade.SurfaceContainerDark,
    surfaceContainerHigh = Kanade.SurfaceContainerHighDark,
    surfaceContainerHighest = Kanade.SurfaceContainerHighestDark,
)
