package theme.scheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import theme.color.Kanon

val KanonLight = lightColorScheme(
    primary = Kanon.PrimaryLight,
    onPrimary = Kanon.OnPrimaryLight,
    primaryContainer = Kanon.PrimaryContainerLight,
    onPrimaryContainer = Kanon.OnPrimaryContainerLight,
    secondary = Kanon.SecondaryLight,
    onSecondary = Kanon.OnSecondaryLight,
    secondaryContainer = Kanon.SecondaryContainerLight,
    onSecondaryContainer = Kanon.OnSecondaryContainerLight,
    tertiary = Kanon.TertiaryLight,
    onTertiary = Kanon.OnTertiaryLight,
    tertiaryContainer = Kanon.TertiaryContainerLight,
    onTertiaryContainer = Kanon.OnTertiaryContainerLight,
    error = Kanon.ErrorLight,
    onError = Kanon.OnErrorLight,
    errorContainer = Kanon.ErrorContainerLight,
    onErrorContainer = Kanon.OnErrorContainerLight,
    background = Kanon.BackgroundLight,
    onBackground = Kanon.OnBackgroundLight,
    surface = Kanon.SurfaceLight,
    onSurface = Kanon.OnSurfaceLight,
    surfaceVariant = Kanon.SurfaceVariantLight,
    onSurfaceVariant = Kanon.OnSurfaceVariantLight,
    outline = Kanon.OutlineLight,
    outlineVariant = Kanon.OutlineVariantLight,
    scrim = Kanon.ScrimLight,
    inverseSurface = Kanon.InverseSurfaceLight,
    inverseOnSurface = Kanon.InverseOnSurfaceLight,
    inversePrimary = Kanon.InversePrimaryLight,
    surfaceDim = Kanon.SurfaceDimLight,
    surfaceBright = Kanon.SurfaceBrightLight,
    surfaceContainerLowest = Kanon.SurfaceContainerLowestLight,
    surfaceContainerLow = Kanon.SurfaceContainerLowLight,
    surfaceContainer = Kanon.SurfaceContainerLight,
    surfaceContainerHigh = Kanon.SurfaceContainerHighLight,
    surfaceContainerHighest = Kanon.SurfaceContainerHighestLight,
)

val KanonDark = darkColorScheme(
    primary = Kanon.PrimaryDark,
    onPrimary = Kanon.OnPrimaryDark,
    primaryContainer = Kanon.PrimaryContainerDark,
    onPrimaryContainer = Kanon.OnPrimaryContainerDark,
    secondary = Kanon.SecondaryDark,
    onSecondary = Kanon.OnSecondaryDark,
    secondaryContainer = Kanon.SecondaryContainerDark,
    onSecondaryContainer = Kanon.OnSecondaryContainerDark,
    tertiary = Kanon.TertiaryDark,
    onTertiary = Kanon.OnTertiaryDark,
    tertiaryContainer = Kanon.TertiaryContainerDark,
    onTertiaryContainer = Kanon.OnTertiaryContainerDark,
    error = Kanon.ErrorDark,
    onError = Kanon.OnErrorDark,
    errorContainer = Kanon.ErrorContainerDark,
    onErrorContainer = Kanon.OnErrorContainerDark,
    background = Kanon.BackgroundDark,
    onBackground = Kanon.OnBackgroundDark,
    surface = Kanon.SurfaceDark,
    onSurface = Kanon.OnSurfaceDark,
    surfaceVariant = Kanon.SurfaceVariantDark,
    onSurfaceVariant = Kanon.OnSurfaceVariantDark,
    outline = Kanon.OutlineDark,
    outlineVariant = Kanon.OutlineVariantDark,
    scrim = Kanon.ScrimDark,
    inverseSurface = Kanon.InverseSurfaceDark,
    inverseOnSurface = Kanon.InverseOnSurfaceDark,
    inversePrimary = Kanon.InversePrimaryDark,
    surfaceDim = Kanon.SurfaceDimDark,
    surfaceBright = Kanon.SurfaceBrightDark,
    surfaceContainerLowest = Kanon.SurfaceContainerLowestDark,
    surfaceContainerLow = Kanon.SurfaceContainerLowDark,
    surfaceContainer = Kanon.SurfaceContainerDark,
    surfaceContainerHigh = Kanon.SurfaceContainerHighDark,
    surfaceContainerHighest = Kanon.SurfaceContainerHighestDark,
)
