package theme.scheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import theme.color.Kotlin

val KotlinLight = lightColorScheme(
    primary = Kotlin.PrimaryLight,
    onPrimary = Kotlin.OnPrimaryLight,
    primaryContainer = Kotlin.PrimaryContainerLight,
    onPrimaryContainer = Kotlin.OnPrimaryContainerLight,
    secondary = Kotlin.SecondaryLight,
    onSecondary = Kotlin.OnSecondaryLight,
    secondaryContainer = Kotlin.SecondaryContainerLight,
    onSecondaryContainer = Kotlin.OnSecondaryContainerLight,
    tertiary = Kotlin.TertiaryLight,
    onTertiary = Kotlin.OnTertiaryLight,
    tertiaryContainer = Kotlin.TertiaryContainerLight,
    onTertiaryContainer = Kotlin.OnTertiaryContainerLight,
    error = Kotlin.ErrorLight,
    onError = Kotlin.OnErrorLight,
    errorContainer = Kotlin.ErrorContainerLight,
    onErrorContainer = Kotlin.OnErrorContainerLight,
    background = Kotlin.BackgroundLight,
    onBackground = Kotlin.OnBackgroundLight,
    surface = Kotlin.SurfaceLight,
    onSurface = Kotlin.OnSurfaceLight,
    surfaceVariant = Kotlin.SurfaceVariantLight,
    onSurfaceVariant = Kotlin.OnSurfaceVariantLight,
    outline = Kotlin.OutlineLight,
    outlineVariant = Kotlin.OutlineVariantLight,
    scrim = Kotlin.ScrimLight,
    inverseSurface = Kotlin.InverseSurfaceLight,
    inverseOnSurface = Kotlin.InverseOnSurfaceLight,
    inversePrimary = Kotlin.InversePrimaryLight,
    surfaceDim = Kotlin.SurfaceDimLight,
    surfaceBright = Kotlin.SurfaceBrightLight,
    surfaceContainerLowest = Kotlin.SurfaceContainerLowestLight,
    surfaceContainerLow = Kotlin.SurfaceContainerLowLight,
    surfaceContainer = Kotlin.SurfaceContainerLight,
    surfaceContainerHigh = Kotlin.SurfaceContainerHighLight,
    surfaceContainerHighest = Kotlin.SurfaceContainerHighestLight,
)

val KotlinDark = darkColorScheme(
    primary = Kotlin.PrimaryDark,
    onPrimary = Kotlin.OnPrimaryDark,
    primaryContainer = Kotlin.PrimaryContainerDark,
    onPrimaryContainer = Kotlin.OnPrimaryContainerDark,
    secondary = Kotlin.SecondaryDark,
    onSecondary = Kotlin.OnSecondaryDark,
    secondaryContainer = Kotlin.SecondaryContainerDark,
    onSecondaryContainer = Kotlin.OnSecondaryContainerDark,
    tertiary = Kotlin.TertiaryDark,
    onTertiary = Kotlin.OnTertiaryDark,
    tertiaryContainer = Kotlin.TertiaryContainerDark,
    onTertiaryContainer = Kotlin.OnTertiaryContainerDark,
    error = Kotlin.ErrorDark,
    onError = Kotlin.OnErrorDark,
    errorContainer = Kotlin.ErrorContainerDark,
    onErrorContainer = Kotlin.OnErrorContainerDark,
    background = Kotlin.BackgroundDark,
    onBackground = Kotlin.OnBackgroundDark,
    surface = Kotlin.SurfaceDark,
    onSurface = Kotlin.OnSurfaceDark,
    surfaceVariant = Kotlin.SurfaceVariantDark,
    onSurfaceVariant = Kotlin.OnSurfaceVariantDark,
    outline = Kotlin.OutlineDark,
    outlineVariant = Kotlin.OutlineVariantDark,
    scrim = Kotlin.ScrimDark,
    inverseSurface = Kotlin.InverseSurfaceDark,
    inverseOnSurface = Kotlin.InverseOnSurfaceDark,
    inversePrimary = Kotlin.InversePrimaryDark,
    surfaceDim = Kotlin.SurfaceDimDark,
    surfaceBright = Kotlin.SurfaceBrightDark,
    surfaceContainerLowest = Kotlin.SurfaceContainerLowestDark,
    surfaceContainerLow = Kotlin.SurfaceContainerLowDark,
    surfaceContainer = Kotlin.SurfaceContainerDark,
    surfaceContainerHigh = Kotlin.SurfaceContainerHighDark,
    surfaceContainerHighest = Kotlin.SurfaceContainerHighestDark,
)
