package theme.scheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import theme.color.Madoka

val MadokaLight = lightColorScheme(
    primary = Madoka.PrimaryLight,
    onPrimary = Madoka.OnPrimaryLight,
    primaryContainer = Madoka.PrimaryContainerLight,
    onPrimaryContainer = Madoka.OnPrimaryContainerLight,
    secondary = Madoka.SecondaryLight,
    onSecondary = Madoka.OnSecondaryLight,
    secondaryContainer = Madoka.SecondaryContainerLight,
    onSecondaryContainer = Madoka.OnSecondaryContainerLight,
    tertiary = Madoka.TertiaryLight,
    onTertiary = Madoka.OnTertiaryLight,
    tertiaryContainer = Madoka.TertiaryContainerLight,
    onTertiaryContainer = Madoka.OnTertiaryContainerLight,
    error = Madoka.ErrorLight,
    onError = Madoka.OnErrorLight,
    errorContainer = Madoka.ErrorContainerLight,
    onErrorContainer = Madoka.OnErrorContainerLight,
    background = Madoka.BackgroundLight,
    onBackground = Madoka.OnBackgroundLight,
    surface = Madoka.SurfaceLight,
    onSurface = Madoka.OnSurfaceLight,
    surfaceVariant = Madoka.SurfaceVariantLight,
    onSurfaceVariant = Madoka.OnSurfaceVariantLight,
    outline = Madoka.OutlineLight,
    outlineVariant = Madoka.OutlineVariantLight,
    scrim = Madoka.ScrimLight,
    inverseSurface = Madoka.InverseSurfaceLight,
    inverseOnSurface = Madoka.InverseOnSurfaceLight,
    inversePrimary = Madoka.InversePrimaryLight,
    surfaceDim = Madoka.SurfaceDimLight,
    surfaceBright = Madoka.SurfaceBrightLight,
    surfaceContainerLowest = Madoka.SurfaceContainerLowestLight,
    surfaceContainerLow = Madoka.SurfaceContainerLowLight,
    surfaceContainer = Madoka.SurfaceContainerLight,
    surfaceContainerHigh = Madoka.SurfaceContainerHighLight,
    surfaceContainerHighest = Madoka.SurfaceContainerHighestLight,
)

val MadokaDark = darkColorScheme(
    primary = Madoka.PrimaryDark,
    onPrimary = Madoka.OnPrimaryDark,
    primaryContainer = Madoka.PrimaryContainerDark,
    onPrimaryContainer = Madoka.OnPrimaryContainerDark,
    secondary = Madoka.SecondaryDark,
    onSecondary = Madoka.OnSecondaryDark,
    secondaryContainer = Madoka.SecondaryContainerDark,
    onSecondaryContainer = Madoka.OnSecondaryContainerDark,
    tertiary = Madoka.TertiaryDark,
    onTertiary = Madoka.OnTertiaryDark,
    tertiaryContainer = Madoka.TertiaryContainerDark,
    onTertiaryContainer = Madoka.OnTertiaryContainerDark,
    error = Madoka.ErrorDark,
    onError = Madoka.OnErrorDark,
    errorContainer = Madoka.ErrorContainerDark,
    onErrorContainer = Madoka.OnErrorContainerDark,
    background = Madoka.BackgroundDark,
    onBackground = Madoka.OnBackgroundDark,
    surface = Madoka.SurfaceDark,
    onSurface = Madoka.OnSurfaceDark,
    surfaceVariant = Madoka.SurfaceVariantDark,
    onSurfaceVariant = Madoka.OnSurfaceVariantDark,
    outline = Madoka.OutlineDark,
    outlineVariant = Madoka.OutlineVariantDark,
    scrim = Madoka.ScrimDark,
    inverseSurface = Madoka.InverseSurfaceDark,
    inverseOnSurface = Madoka.InverseOnSurfaceDark,
    inversePrimary = Madoka.InversePrimaryDark,
    surfaceDim = Madoka.SurfaceDimDark,
    surfaceBright = Madoka.SurfaceBrightDark,
    surfaceContainerLowest = Madoka.SurfaceContainerLowestDark,
    surfaceContainerLow = Madoka.SurfaceContainerLowDark,
    surfaceContainer = Madoka.SurfaceContainerDark,
    surfaceContainerHigh = Madoka.SurfaceContainerHighDark,
    surfaceContainerHighest = Madoka.SurfaceContainerHighestDark,
)
