package theme.scheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import theme.color.Mizuki

val MizukiLight = lightColorScheme(
    primary = Mizuki.PrimaryLight,
    onPrimary = Mizuki.OnPrimaryLight,
    primaryContainer = Mizuki.PrimaryContainerLight,
    onPrimaryContainer = Mizuki.OnPrimaryContainerLight,
    secondary = Mizuki.SecondaryLight,
    onSecondary = Mizuki.OnSecondaryLight,
    secondaryContainer = Mizuki.SecondaryContainerLight,
    onSecondaryContainer = Mizuki.OnSecondaryContainerLight,
    tertiary = Mizuki.TertiaryLight,
    onTertiary = Mizuki.OnTertiaryLight,
    tertiaryContainer = Mizuki.TertiaryContainerLight,
    onTertiaryContainer = Mizuki.OnTertiaryContainerLight,
    error = Mizuki.ErrorLight,
    onError = Mizuki.OnErrorLight,
    errorContainer = Mizuki.ErrorContainerLight,
    onErrorContainer = Mizuki.OnErrorContainerLight,
    background = Mizuki.BackgroundLight,
    onBackground = Mizuki.OnBackgroundLight,
    surface = Mizuki.SurfaceLight,
    onSurface = Mizuki.OnSurfaceLight,
    surfaceVariant = Mizuki.SurfaceVariantLight,
    onSurfaceVariant = Mizuki.OnSurfaceVariantLight,
    outline = Mizuki.OutlineLight,
    outlineVariant = Mizuki.OutlineVariantLight,
    scrim = Mizuki.ScrimLight,
    inverseSurface = Mizuki.InverseSurfaceLight,
    inverseOnSurface = Mizuki.InverseOnSurfaceLight,
    inversePrimary = Mizuki.InversePrimaryLight,
    surfaceDim = Mizuki.SurfaceDimLight,
    surfaceBright = Mizuki.SurfaceBrightLight,
    surfaceContainerLowest = Mizuki.SurfaceContainerLowestLight,
    surfaceContainerLow = Mizuki.SurfaceContainerLowLight,
    surfaceContainer = Mizuki.SurfaceContainerLight,
    surfaceContainerHigh = Mizuki.SurfaceContainerHighLight,
    surfaceContainerHighest = Mizuki.SurfaceContainerHighestLight,
)

val MizukiDark = darkColorScheme(
    primary = Mizuki.PrimaryDark,
    onPrimary = Mizuki.OnPrimaryDark,
    primaryContainer = Mizuki.PrimaryContainerDark,
    onPrimaryContainer = Mizuki.OnPrimaryContainerDark,
    secondary = Mizuki.SecondaryDark,
    onSecondary = Mizuki.OnSecondaryDark,
    secondaryContainer = Mizuki.SecondaryContainerDark,
    onSecondaryContainer = Mizuki.OnSecondaryContainerDark,
    tertiary = Mizuki.TertiaryDark,
    onTertiary = Mizuki.OnTertiaryDark,
    tertiaryContainer = Mizuki.TertiaryContainerDark,
    onTertiaryContainer = Mizuki.OnTertiaryContainerDark,
    error = Mizuki.ErrorDark,
    onError = Mizuki.OnErrorDark,
    errorContainer = Mizuki.ErrorContainerDark,
    onErrorContainer = Mizuki.OnErrorContainerDark,
    background = Mizuki.BackgroundDark,
    onBackground = Mizuki.OnBackgroundDark,
    surface = Mizuki.SurfaceDark,
    onSurface = Mizuki.OnSurfaceDark,
    surfaceVariant = Mizuki.SurfaceVariantDark,
    onSurfaceVariant = Mizuki.OnSurfaceVariantDark,
    outline = Mizuki.OutlineDark,
    outlineVariant = Mizuki.OutlineVariantDark,
    scrim = Mizuki.ScrimDark,
    inverseSurface = Mizuki.InverseSurfaceDark,
    inverseOnSurface = Mizuki.InverseOnSurfaceDark,
    inversePrimary = Mizuki.InversePrimaryDark,
    surfaceDim = Mizuki.SurfaceDimDark,
    surfaceBright = Mizuki.SurfaceBrightDark,
    surfaceContainerLowest = Mizuki.SurfaceContainerLowestDark,
    surfaceContainerLow = Mizuki.SurfaceContainerLowDark,
    surfaceContainer = Mizuki.SurfaceContainerDark,
    surfaceContainerHigh = Mizuki.SurfaceContainerHighDark,
    surfaceContainerHighest = Mizuki.SurfaceContainerHighestDark,
)
