package theme.scheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import theme.color.Rails

val RailsLight = lightColorScheme(
    primary = Rails.PrimaryLight,
    onPrimary = Rails.OnPrimaryLight,
    primaryContainer = Rails.PrimaryContainerLight,
    onPrimaryContainer = Rails.OnPrimaryContainerLight,
    secondary = Rails.SecondaryLight,
    onSecondary = Rails.OnSecondaryLight,
    secondaryContainer = Rails.SecondaryContainerLight,
    onSecondaryContainer = Rails.OnSecondaryContainerLight,
    tertiary = Rails.TertiaryLight,
    onTertiary = Rails.OnTertiaryLight,
    tertiaryContainer = Rails.TertiaryContainerLight,
    onTertiaryContainer = Rails.OnTertiaryContainerLight,
    error = Rails.ErrorLight,
    onError = Rails.OnErrorLight,
    errorContainer = Rails.ErrorContainerLight,
    onErrorContainer = Rails.OnErrorContainerLight,
    background = Rails.BackgroundLight,
    onBackground = Rails.OnBackgroundLight,
    surface = Rails.SurfaceLight,
    onSurface = Rails.OnSurfaceLight,
    surfaceVariant = Rails.SurfaceVariantLight,
    onSurfaceVariant = Rails.OnSurfaceVariantLight,
    outline = Rails.OutlineLight,
    outlineVariant = Rails.OutlineVariantLight,
    scrim = Rails.ScrimLight,
    inverseSurface = Rails.InverseSurfaceLight,
    inverseOnSurface = Rails.InverseOnSurfaceLight,
    inversePrimary = Rails.InversePrimaryLight,
    surfaceDim = Rails.SurfaceDimLight,
    surfaceBright = Rails.SurfaceBrightLight,
    surfaceContainerLowest = Rails.SurfaceContainerLowestLight,
    surfaceContainerLow = Rails.SurfaceContainerLowLight,
    surfaceContainer = Rails.SurfaceContainerLight,
    surfaceContainerHigh = Rails.SurfaceContainerHighLight,
    surfaceContainerHighest = Rails.SurfaceContainerHighestLight,
)

val RailsDark = darkColorScheme(
    primary = Rails.PrimaryDark,
    onPrimary = Rails.OnPrimaryDark,
    primaryContainer = Rails.PrimaryContainerDark,
    onPrimaryContainer = Rails.OnPrimaryContainerDark,
    secondary = Rails.SecondaryDark,
    onSecondary = Rails.OnSecondaryDark,
    secondaryContainer = Rails.SecondaryContainerDark,
    onSecondaryContainer = Rails.OnSecondaryContainerDark,
    tertiary = Rails.TertiaryDark,
    onTertiary = Rails.OnTertiaryDark,
    tertiaryContainer = Rails.TertiaryContainerDark,
    onTertiaryContainer = Rails.OnTertiaryContainerDark,
    error = Rails.ErrorDark,
    onError = Rails.OnErrorDark,
    errorContainer = Rails.ErrorContainerDark,
    onErrorContainer = Rails.OnErrorContainerDark,
    background = Rails.BackgroundDark,
    onBackground = Rails.OnBackgroundDark,
    surface = Rails.SurfaceDark,
    onSurface = Rails.OnSurfaceDark,
    surfaceVariant = Rails.SurfaceVariantDark,
    onSurfaceVariant = Rails.OnSurfaceVariantDark,
    outline = Rails.OutlineDark,
    outlineVariant = Rails.OutlineVariantDark,
    scrim = Rails.ScrimDark,
    inverseSurface = Rails.InverseSurfaceDark,
    inverseOnSurface = Rails.InverseOnSurfaceDark,
    inversePrimary = Rails.InversePrimaryDark,
    surfaceDim = Rails.SurfaceDimDark,
    surfaceBright = Rails.SurfaceBrightDark,
    surfaceContainerLowest = Rails.SurfaceContainerLowestDark,
    surfaceContainerLow = Rails.SurfaceContainerLowDark,
    surfaceContainer = Rails.SurfaceContainerDark,
    surfaceContainerHigh = Rails.SurfaceContainerHighDark,
    surfaceContainerHighest = Rails.SurfaceContainerHighestDark,
)
