package theme.scheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import theme.color.React

val ReactLight = lightColorScheme(
    primary = React.PrimaryLight,
    onPrimary = React.OnPrimaryLight,
    primaryContainer = React.PrimaryContainerLight,
    onPrimaryContainer = React.OnPrimaryContainerLight,
    secondary = React.SecondaryLight,
    onSecondary = React.OnSecondaryLight,
    secondaryContainer = React.SecondaryContainerLight,
    onSecondaryContainer = React.OnSecondaryContainerLight,
    tertiary = React.TertiaryLight,
    onTertiary = React.OnTertiaryLight,
    tertiaryContainer = React.TertiaryContainerLight,
    onTertiaryContainer = React.OnTertiaryContainerLight,
    error = React.ErrorLight,
    onError = React.OnErrorLight,
    errorContainer = React.ErrorContainerLight,
    onErrorContainer = React.OnErrorContainerLight,
    background = React.BackgroundLight,
    onBackground = React.OnBackgroundLight,
    surface = React.SurfaceLight,
    onSurface = React.OnSurfaceLight,
    surfaceVariant = React.SurfaceVariantLight,
    onSurfaceVariant = React.OnSurfaceVariantLight,
    outline = React.OutlineLight,
    outlineVariant = React.OutlineVariantLight,
    scrim = React.ScrimLight,
    inverseSurface = React.InverseSurfaceLight,
    inverseOnSurface = React.InverseOnSurfaceLight,
    inversePrimary = React.InversePrimaryLight,
    surfaceDim = React.SurfaceDimLight,
    surfaceBright = React.SurfaceBrightLight,
    surfaceContainerLowest = React.SurfaceContainerLowestLight,
    surfaceContainerLow = React.SurfaceContainerLowLight,
    surfaceContainer = React.SurfaceContainerLight,
    surfaceContainerHigh = React.SurfaceContainerHighLight,
    surfaceContainerHighest = React.SurfaceContainerHighestLight,
)

val ReactDark = darkColorScheme(
    primary = React.PrimaryDark,
    onPrimary = React.OnPrimaryDark,
    primaryContainer = React.PrimaryContainerDark,
    onPrimaryContainer = React.OnPrimaryContainerDark,
    secondary = React.SecondaryDark,
    onSecondary = React.OnSecondaryDark,
    secondaryContainer = React.SecondaryContainerDark,
    onSecondaryContainer = React.OnSecondaryContainerDark,
    tertiary = React.TertiaryDark,
    onTertiary = React.OnTertiaryDark,
    tertiaryContainer = React.TertiaryContainerDark,
    onTertiaryContainer = React.OnTertiaryContainerDark,
    error = React.ErrorDark,
    onError = React.OnErrorDark,
    errorContainer = React.ErrorContainerDark,
    onErrorContainer = React.OnErrorContainerDark,
    background = React.BackgroundDark,
    onBackground = React.OnBackgroundDark,
    surface = React.SurfaceDark,
    onSurface = React.OnSurfaceDark,
    surfaceVariant = React.SurfaceVariantDark,
    onSurfaceVariant = React.OnSurfaceVariantDark,
    outline = React.OutlineDark,
    outlineVariant = React.OutlineVariantDark,
    scrim = React.ScrimDark,
    inverseSurface = React.InverseSurfaceDark,
    inverseOnSurface = React.InverseOnSurfaceDark,
    inversePrimary = React.InversePrimaryDark,
    surfaceDim = React.SurfaceDimDark,
    surfaceBright = React.SurfaceBrightDark,
    surfaceContainerLowest = React.SurfaceContainerLowestDark,
    surfaceContainerLow = React.SurfaceContainerLowDark,
    surfaceContainer = React.SurfaceContainerDark,
    surfaceContainerHigh = React.SurfaceContainerHighDark,
    surfaceContainerHighest = React.SurfaceContainerHighestDark,
)
