package theme.scheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import theme.color.Sayaka

val SayakaLight = lightColorScheme(
    primary = Sayaka.PrimaryLight,
    onPrimary = Sayaka.OnPrimaryLight,
    primaryContainer = Sayaka.PrimaryContainerLight,
    onPrimaryContainer = Sayaka.OnPrimaryContainerLight,
    secondary = Sayaka.SecondaryLight,
    onSecondary = Sayaka.OnSecondaryLight,
    secondaryContainer = Sayaka.SecondaryContainerLight,
    onSecondaryContainer = Sayaka.OnSecondaryContainerLight,
    tertiary = Sayaka.TertiaryLight,
    onTertiary = Sayaka.OnTertiaryLight,
    tertiaryContainer = Sayaka.TertiaryContainerLight,
    onTertiaryContainer = Sayaka.OnTertiaryContainerLight,
    error = Sayaka.ErrorLight,
    onError = Sayaka.OnErrorLight,
    errorContainer = Sayaka.ErrorContainerLight,
    onErrorContainer = Sayaka.OnErrorContainerLight,
    background = Sayaka.BackgroundLight,
    onBackground = Sayaka.OnBackgroundLight,
    surface = Sayaka.SurfaceLight,
    onSurface = Sayaka.OnSurfaceLight,
    surfaceVariant = Sayaka.SurfaceVariantLight,
    onSurfaceVariant = Sayaka.OnSurfaceVariantLight,
    outline = Sayaka.OutlineLight,
    outlineVariant = Sayaka.OutlineVariantLight,
    scrim = Sayaka.ScrimLight,
    inverseSurface = Sayaka.InverseSurfaceLight,
    inverseOnSurface = Sayaka.InverseOnSurfaceLight,
    inversePrimary = Sayaka.InversePrimaryLight,
    surfaceDim = Sayaka.SurfaceDimLight,
    surfaceBright = Sayaka.SurfaceBrightLight,
    surfaceContainerLowest = Sayaka.SurfaceContainerLowestLight,
    surfaceContainerLow = Sayaka.SurfaceContainerLowLight,
    surfaceContainer = Sayaka.SurfaceContainerLight,
    surfaceContainerHigh = Sayaka.SurfaceContainerHighLight,
    surfaceContainerHighest = Sayaka.SurfaceContainerHighestLight,
)

val SayakaDark = darkColorScheme(
    primary = Sayaka.PrimaryDark,
    onPrimary = Sayaka.OnPrimaryDark,
    primaryContainer = Sayaka.PrimaryContainerDark,
    onPrimaryContainer = Sayaka.OnPrimaryContainerDark,
    secondary = Sayaka.SecondaryDark,
    onSecondary = Sayaka.OnSecondaryDark,
    secondaryContainer = Sayaka.SecondaryContainerDark,
    onSecondaryContainer = Sayaka.OnSecondaryContainerDark,
    tertiary = Sayaka.TertiaryDark,
    onTertiary = Sayaka.OnTertiaryDark,
    tertiaryContainer = Sayaka.TertiaryContainerDark,
    onTertiaryContainer = Sayaka.OnTertiaryContainerDark,
    error = Sayaka.ErrorDark,
    onError = Sayaka.OnErrorDark,
    errorContainer = Sayaka.ErrorContainerDark,
    onErrorContainer = Sayaka.OnErrorContainerDark,
    background = Sayaka.BackgroundDark,
    onBackground = Sayaka.OnBackgroundDark,
    surface = Sayaka.SurfaceDark,
    onSurface = Sayaka.OnSurfaceDark,
    surfaceVariant = Sayaka.SurfaceVariantDark,
    onSurfaceVariant = Sayaka.OnSurfaceVariantDark,
    outline = Sayaka.OutlineDark,
    outlineVariant = Sayaka.OutlineVariantDark,
    scrim = Sayaka.ScrimDark,
    inverseSurface = Sayaka.InverseSurfaceDark,
    inverseOnSurface = Sayaka.InverseOnSurfaceDark,
    inversePrimary = Sayaka.InversePrimaryDark,
    surfaceDim = Sayaka.SurfaceDimDark,
    surfaceBright = Sayaka.SurfaceBrightDark,
    surfaceContainerLowest = Sayaka.SurfaceContainerLowestDark,
    surfaceContainerLow = Sayaka.SurfaceContainerLowDark,
    surfaceContainer = Sayaka.SurfaceContainerDark,
    surfaceContainerHigh = Sayaka.SurfaceContainerHighDark,
    surfaceContainerHighest = Sayaka.SurfaceContainerHighestDark,
)
