package theme.scheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import theme.color.Temari

val TemariLight = lightColorScheme(
    primary = Temari.PrimaryLight,
    onPrimary = Temari.OnPrimaryLight,
    primaryContainer = Temari.PrimaryContainerLight,
    onPrimaryContainer = Temari.OnPrimaryContainerLight,
    secondary = Temari.SecondaryLight,
    onSecondary = Temari.OnSecondaryLight,
    secondaryContainer = Temari.SecondaryContainerLight,
    onSecondaryContainer = Temari.OnSecondaryContainerLight,
    tertiary = Temari.TertiaryLight,
    onTertiary = Temari.OnTertiaryLight,
    tertiaryContainer = Temari.TertiaryContainerLight,
    onTertiaryContainer = Temari.OnTertiaryContainerLight,
    error = Temari.ErrorLight,
    onError = Temari.OnErrorLight,
    errorContainer = Temari.ErrorContainerLight,
    onErrorContainer = Temari.OnErrorContainerLight,
    background = Temari.BackgroundLight,
    onBackground = Temari.OnBackgroundLight,
    surface = Temari.SurfaceLight,
    onSurface = Temari.OnSurfaceLight,
    surfaceVariant = Temari.SurfaceVariantLight,
    onSurfaceVariant = Temari.OnSurfaceVariantLight,
    outline = Temari.OutlineLight,
    outlineVariant = Temari.OutlineVariantLight,
    scrim = Temari.ScrimLight,
    inverseSurface = Temari.InverseSurfaceLight,
    inverseOnSurface = Temari.InverseOnSurfaceLight,
    inversePrimary = Temari.InversePrimaryLight,
    surfaceDim = Temari.SurfaceDimLight,
    surfaceBright = Temari.SurfaceBrightLight,
    surfaceContainerLowest = Temari.SurfaceContainerLowestLight,
    surfaceContainerLow = Temari.SurfaceContainerLowLight,
    surfaceContainer = Temari.SurfaceContainerLight,
    surfaceContainerHigh = Temari.SurfaceContainerHighLight,
    surfaceContainerHighest = Temari.SurfaceContainerHighestLight,
)

val TemariDark = darkColorScheme(
    primary = Temari.PrimaryDark,
    onPrimary = Temari.OnPrimaryDark,
    primaryContainer = Temari.PrimaryContainerDark,
    onPrimaryContainer = Temari.OnPrimaryContainerDark,
    secondary = Temari.SecondaryDark,
    onSecondary = Temari.OnSecondaryDark,
    secondaryContainer = Temari.SecondaryContainerDark,
    onSecondaryContainer = Temari.OnSecondaryContainerDark,
    tertiary = Temari.TertiaryDark,
    onTertiary = Temari.OnTertiaryDark,
    tertiaryContainer = Temari.TertiaryContainerDark,
    onTertiaryContainer = Temari.OnTertiaryContainerDark,
    error = Temari.ErrorDark,
    onError = Temari.OnErrorDark,
    errorContainer = Temari.ErrorContainerDark,
    onErrorContainer = Temari.OnErrorContainerDark,
    background = Temari.BackgroundDark,
    onBackground = Temari.OnBackgroundDark,
    surface = Temari.SurfaceDark,
    onSurface = Temari.OnSurfaceDark,
    surfaceVariant = Temari.SurfaceVariantDark,
    onSurfaceVariant = Temari.OnSurfaceVariantDark,
    outline = Temari.OutlineDark,
    outlineVariant = Temari.OutlineVariantDark,
    scrim = Temari.ScrimDark,
    inverseSurface = Temari.InverseSurfaceDark,
    inverseOnSurface = Temari.InverseOnSurfaceDark,
    inversePrimary = Temari.InversePrimaryDark,
    surfaceDim = Temari.SurfaceDimDark,
    surfaceBright = Temari.SurfaceBrightDark,
    surfaceContainerLowest = Temari.SurfaceContainerLowestDark,
    surfaceContainerLow = Temari.SurfaceContainerLowDark,
    surfaceContainer = Temari.SurfaceContainerDark,
    surfaceContainerHigh = Temari.SurfaceContainerHighDark,
    surfaceContainerHighest = Temari.SurfaceContainerHighestDark,
)
