package theme.scheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import theme.color.You

val YouLight = lightColorScheme(
    primary = You.PrimaryLight,
    onPrimary = You.OnPrimaryLight,
    primaryContainer = You.PrimaryContainerLight,
    onPrimaryContainer = You.OnPrimaryContainerLight,
    secondary = You.SecondaryLight,
    onSecondary = You.OnSecondaryLight,
    secondaryContainer = You.SecondaryContainerLight,
    onSecondaryContainer = You.OnSecondaryContainerLight,
    tertiary = You.TertiaryLight,
    onTertiary = You.OnTertiaryLight,
    tertiaryContainer = You.TertiaryContainerLight,
    onTertiaryContainer = You.OnTertiaryContainerLight,
    error = You.ErrorLight,
    onError = You.OnErrorLight,
    errorContainer = You.ErrorContainerLight,
    onErrorContainer = You.OnErrorContainerLight,
    background = You.BackgroundLight,
    onBackground = You.OnBackgroundLight,
    surface = You.SurfaceLight,
    onSurface = You.OnSurfaceLight,
    surfaceVariant = You.SurfaceVariantLight,
    onSurfaceVariant = You.OnSurfaceVariantLight,
    outline = You.OutlineLight,
    outlineVariant = You.OutlineVariantLight,
    scrim = You.ScrimLight,
    inverseSurface = You.InverseSurfaceLight,
    inverseOnSurface = You.InverseOnSurfaceLight,
    inversePrimary = You.InversePrimaryLight,
    surfaceDim = You.SurfaceDimLight,
    surfaceBright = You.SurfaceBrightLight,
    surfaceContainerLowest = You.SurfaceContainerLowestLight,
    surfaceContainerLow = You.SurfaceContainerLowLight,
    surfaceContainer = You.SurfaceContainerLight,
    surfaceContainerHigh = You.SurfaceContainerHighLight,
    surfaceContainerHighest = You.SurfaceContainerHighestLight,
)

val YouDark = darkColorScheme(
    primary = You.PrimaryDark,
    onPrimary = You.OnPrimaryDark,
    primaryContainer = You.PrimaryContainerDark,
    onPrimaryContainer = You.OnPrimaryContainerDark,
    secondary = You.SecondaryDark,
    onSecondary = You.OnSecondaryDark,
    secondaryContainer = You.SecondaryContainerDark,
    onSecondaryContainer = You.OnSecondaryContainerDark,
    tertiary = You.TertiaryDark,
    onTertiary = You.OnTertiaryDark,
    tertiaryContainer = You.TertiaryContainerDark,
    onTertiaryContainer = You.OnTertiaryContainerDark,
    error = You.ErrorDark,
    onError = You.OnErrorDark,
    errorContainer = You.ErrorContainerDark,
    onErrorContainer = You.OnErrorContainerDark,
    background = You.BackgroundDark,
    onBackground = You.OnBackgroundDark,
    surface = You.SurfaceDark,
    onSurface = You.OnSurfaceDark,
    surfaceVariant = You.SurfaceVariantDark,
    onSurfaceVariant = You.OnSurfaceVariantDark,
    outline = You.OutlineDark,
    outlineVariant = You.OutlineVariantDark,
    scrim = You.ScrimDark,
    inverseSurface = You.InverseSurfaceDark,
    inverseOnSurface = You.InverseOnSurfaceDark,
    inversePrimary = You.InversePrimaryDark,
    surfaceDim = You.SurfaceDimDark,
    surfaceBright = You.SurfaceBrightDark,
    surfaceContainerLowest = You.SurfaceContainerLowestDark,
    surfaceContainerLow = You.SurfaceContainerLowDark,
    surfaceContainer = You.SurfaceContainerDark,
    surfaceContainerHigh = You.SurfaceContainerHighDark,
    surfaceContainerHighest = You.SurfaceContainerHighestDark,
)
