package theme.scheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import theme.color.Yu

val YuLight = lightColorScheme(
    primary = Yu.PrimaryLight,
    onPrimary = Yu.OnPrimaryLight,
    primaryContainer = Yu.PrimaryContainerLight,
    onPrimaryContainer = Yu.OnPrimaryContainerLight,
    secondary = Yu.SecondaryLight,
    onSecondary = Yu.OnSecondaryLight,
    secondaryContainer = Yu.SecondaryContainerLight,
    onSecondaryContainer = Yu.OnSecondaryContainerLight,
    tertiary = Yu.TertiaryLight,
    onTertiary = Yu.OnTertiaryLight,
    tertiaryContainer = Yu.TertiaryContainerLight,
    onTertiaryContainer = Yu.OnTertiaryContainerLight,
    error = Yu.ErrorLight,
    onError = Yu.OnErrorLight,
    errorContainer = Yu.ErrorContainerLight,
    onErrorContainer = Yu.OnErrorContainerLight,
    background = Yu.BackgroundLight,
    onBackground = Yu.OnBackgroundLight,
    surface = Yu.SurfaceLight,
    onSurface = Yu.OnSurfaceLight,
    surfaceVariant = Yu.SurfaceVariantLight,
    onSurfaceVariant = Yu.OnSurfaceVariantLight,
    outline = Yu.OutlineLight,
    outlineVariant = Yu.OutlineVariantLight,
    scrim = Yu.ScrimLight,
    inverseSurface = Yu.InverseSurfaceLight,
    inverseOnSurface = Yu.InverseOnSurfaceLight,
    inversePrimary = Yu.InversePrimaryLight,
    surfaceDim = Yu.SurfaceDimLight,
    surfaceBright = Yu.SurfaceBrightLight,
    surfaceContainerLowest = Yu.SurfaceContainerLowestLight,
    surfaceContainerLow = Yu.SurfaceContainerLowLight,
    surfaceContainer = Yu.SurfaceContainerLight,
    surfaceContainerHigh = Yu.SurfaceContainerHighLight,
    surfaceContainerHighest = Yu.SurfaceContainerHighestLight,
)

val YuDark = darkColorScheme(
    primary = Yu.PrimaryDark,
    onPrimary = Yu.OnPrimaryDark,
    primaryContainer = Yu.PrimaryContainerDark,
    onPrimaryContainer = Yu.OnPrimaryContainerDark,
    secondary = Yu.SecondaryDark,
    onSecondary = Yu.OnSecondaryDark,
    secondaryContainer = Yu.SecondaryContainerDark,
    onSecondaryContainer = Yu.OnSecondaryContainerDark,
    tertiary = Yu.TertiaryDark,
    onTertiary = Yu.OnTertiaryDark,
    tertiaryContainer = Yu.TertiaryContainerDark,
    onTertiaryContainer = Yu.OnTertiaryContainerDark,
    error = Yu.ErrorDark,
    onError = Yu.OnErrorDark,
    errorContainer = Yu.ErrorContainerDark,
    onErrorContainer = Yu.OnErrorContainerDark,
    background = Yu.BackgroundDark,
    onBackground = Yu.OnBackgroundDark,
    surface = Yu.SurfaceDark,
    onSurface = Yu.OnSurfaceDark,
    surfaceVariant = Yu.SurfaceVariantDark,
    onSurfaceVariant = Yu.OnSurfaceVariantDark,
    outline = Yu.OutlineDark,
    outlineVariant = Yu.OutlineVariantDark,
    scrim = Yu.ScrimDark,
    inverseSurface = Yu.InverseSurfaceDark,
    inverseOnSurface = Yu.InverseOnSurfaceDark,
    inversePrimary = Yu.InversePrimaryDark,
    surfaceDim = Yu.SurfaceDimDark,
    surfaceBright = Yu.SurfaceBrightDark,
    surfaceContainerLowest = Yu.SurfaceContainerLowestDark,
    surfaceContainerLow = Yu.SurfaceContainerLowDark,
    surfaceContainer = Yu.SurfaceContainerDark,
    surfaceContainerHigh = Yu.SurfaceContainerHighDark,
    surfaceContainerHighest = Yu.SurfaceContainerHighestDark,
)
