package theme.scheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import theme.color.Yuika

val YuikaLight = lightColorScheme(
    primary = Yuika.PrimaryLight,
    onPrimary = Yuika.OnPrimaryLight,
    primaryContainer = Yuika.PrimaryContainerLight,
    onPrimaryContainer = Yuika.OnPrimaryContainerLight,
    secondary = Yuika.SecondaryLight,
    onSecondary = Yuika.OnSecondaryLight,
    secondaryContainer = Yuika.SecondaryContainerLight,
    onSecondaryContainer = Yuika.OnSecondaryContainerLight,
    tertiary = Yuika.TertiaryLight,
    onTertiary = Yuika.OnTertiaryLight,
    tertiaryContainer = Yuika.TertiaryContainerLight,
    onTertiaryContainer = Yuika.OnTertiaryContainerLight,
    error = Yuika.ErrorLight,
    onError = Yuika.OnErrorLight,
    errorContainer = Yuika.ErrorContainerLight,
    onErrorContainer = Yuika.OnErrorContainerLight,
    background = Yuika.BackgroundLight,
    onBackground = Yuika.OnBackgroundLight,
    surface = Yuika.SurfaceLight,
    onSurface = Yuika.OnSurfaceLight,
    surfaceVariant = Yuika.SurfaceVariantLight,
    onSurfaceVariant = Yuika.OnSurfaceVariantLight,
    outline = Yuika.OutlineLight,
    outlineVariant = Yuika.OutlineVariantLight,
    scrim = Yuika.ScrimLight,
    inverseSurface = Yuika.InverseSurfaceLight,
    inverseOnSurface = Yuika.InverseOnSurfaceLight,
    inversePrimary = Yuika.InversePrimaryLight,
    surfaceDim = Yuika.SurfaceDimLight,
    surfaceBright = Yuika.SurfaceBrightLight,
    surfaceContainerLowest = Yuika.SurfaceContainerLowestLight,
    surfaceContainerLow = Yuika.SurfaceContainerLowLight,
    surfaceContainer = Yuika.SurfaceContainerLight,
    surfaceContainerHigh = Yuika.SurfaceContainerHighLight,
    surfaceContainerHighest = Yuika.SurfaceContainerHighestLight,
)

val YuikaDark = darkColorScheme(
    primary = Yuika.PrimaryDark,
    onPrimary = Yuika.OnPrimaryDark,
    primaryContainer = Yuika.PrimaryContainerDark,
    onPrimaryContainer = Yuika.OnPrimaryContainerDark,
    secondary = Yuika.SecondaryDark,
    onSecondary = Yuika.OnSecondaryDark,
    secondaryContainer = Yuika.SecondaryContainerDark,
    onSecondaryContainer = Yuika.OnSecondaryContainerDark,
    tertiary = Yuika.TertiaryDark,
    onTertiary = Yuika.OnTertiaryDark,
    tertiaryContainer = Yuika.TertiaryContainerDark,
    onTertiaryContainer = Yuika.OnTertiaryContainerDark,
    error = Yuika.ErrorDark,
    onError = Yuika.OnErrorDark,
    errorContainer = Yuika.ErrorContainerDark,
    onErrorContainer = Yuika.OnErrorContainerDark,
    background = Yuika.BackgroundDark,
    onBackground = Yuika.OnBackgroundDark,
    surface = Yuika.SurfaceDark,
    onSurface = Yuika.OnSurfaceDark,
    surfaceVariant = Yuika.SurfaceVariantDark,
    onSurfaceVariant = Yuika.OnSurfaceVariantDark,
    outline = Yuika.OutlineDark,
    outlineVariant = Yuika.OutlineVariantDark,
    scrim = Yuika.ScrimDark,
    inverseSurface = Yuika.InverseSurfaceDark,
    inverseOnSurface = Yuika.InverseOnSurfaceDark,
    inversePrimary = Yuika.InversePrimaryDark,
    surfaceDim = Yuika.SurfaceDimDark,
    surfaceBright = Yuika.SurfaceBrightDark,
    surfaceContainerLowest = Yuika.SurfaceContainerLowestDark,
    surfaceContainerLow = Yuika.SurfaceContainerLowDark,
    surfaceContainer = Yuika.SurfaceContainerDark,
    surfaceContainerHigh = Yuika.SurfaceContainerHighDark,
    surfaceContainerHighest = Yuika.SurfaceContainerHighestDark,
)
