package theme.color

import androidx.compose.ui.graphics.Color

object Android {
    val PrimaryLight = Color(0xFF2E6A44)
    val OnPrimaryLight = Color(0xFFFFFFFF)
    val PrimaryContainerLight = Color(0xFFB1F1C1)
    val OnPrimaryContainerLight = Color(0xFF00210E)
    val SecondaryLight = Color(0xFF4F6353)
    val OnSecondaryLight = Color(0xFFFFFFFF)
    val SecondaryContainerLight = Color(0xFFD2E8D4)
    val OnSecondaryContainerLight = Color(0xFF0D1F13)
    val TertiaryLight = Color(0xFF3A646F)
    val OnTertiaryLight = Color(0xFFFFFFFF)
    val TertiaryContainerLight = Color(0xFFBEEAF6)
    val OnTertiaryContainerLight = Color(0xFF001F26)
    val ErrorLight = Color(0xFFBA1A1A)
    val OnErrorLight = Color(0xFFFFFFFF)
    val ErrorContainerLight = Color(0xFFFFDAD6)
    val OnErrorContainerLight = Color(0xFF410002)
    val BackgroundLight = Color(0xFFF6FBF3)
    val OnBackgroundLight = Color(0xFF181D18)
    val SurfaceLight = Color(0xFFF6FBF3)
    val OnSurfaceLight = Color(0xFF181D18)
    val SurfaceVariantLight = Color(0xFFDDE5DB)
    val OnSurfaceVariantLight = Color(0xFF414942)
    val OutlineLight = Color(0xFF717971)
    val OutlineVariantLight = Color(0xFFC0C9BF)
    val ScrimLight = Color(0xFF000000)
    val InverseSurfaceLight = Color(0xFF2C322D)
    val InverseOnSurfaceLight = Color(0xFFEDF2EB)
    val InversePrimaryLight = Color(0xFF96D5A7)
    val SurfaceDimLight = Color(0xFFD6DBD4)
    val SurfaceBrightLight = Color(0xFFF6FBF3)
    val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
    val SurfaceContainerLowLight = Color(0xFFF0F5ED)
    val SurfaceContainerLight = Color(0xFFEAEFE8)
    val SurfaceContainerHighLight = Color(0xFFE5EAE2)
    val SurfaceContainerHighestLight = Color(0xFFDFE4DC)

    val PrimaryDark = Color(0xFF96D5A7)
    val OnPrimaryDark = Color(0xFF00391C)
    val PrimaryContainerDark = Color(0xFF11512E)
    val OnPrimaryContainerDark = Color(0xFFB1F1C1)
    val SecondaryDark = Color(0xFFB6CCB9)
    val OnSecondaryDark = Color(0xFF223527)
    val SecondaryContainerDark = Color(0xFF384B3C)
    val OnSecondaryContainerDark = Color(0xFFD2E8D4)
    val TertiaryDark = Color(0xFFA2CEDA)
    val OnTertiaryDark = Color(0xFF023640)
    val TertiaryContainerDark = Color(0xFF214C57)
    val OnTertiaryContainerDark = Color(0xFFBEEAF6)
    val ErrorDark = Color(0xFFFFB4AB)
    val OnErrorDark = Color(0xFF690005)
    val ErrorContainerDark = Color(0xFF93000A)
    val OnErrorContainerDark = Color(0xFFFFDAD6)
    val BackgroundDark = Color(0xFF101510)
    val OnBackgroundDark = Color(0xFFDFE4DC)
    val SurfaceDark = Color(0xFF101510)
    val OnSurfaceDark = Color(0xFFDFE4DC)
    val SurfaceVariantDark = Color(0xFF414942)
    val OnSurfaceVariantDark = Color(0xFFC0C9BF)
    val OutlineDark = Color(0xFF8B938A)
    val OutlineVariantDark = Color(0xFF414942)
    val ScrimDark = Color(0xFF000000)
    val InverseSurfaceDark = Color(0xFFDFE4DC)
    val InverseOnSurfaceDark = Color(0xFF2C322D)
    val InversePrimaryDark = Color(0xFF2E6A44)
    val SurfaceDimDark = Color(0xFF101510)
    val SurfaceBrightDark = Color(0xFF353A35)
    val SurfaceContainerLowestDark = Color(0xFF0A0F0B)
    val SurfaceContainerLowDark = Color(0xFF181D18)
    val SurfaceContainerDark = Color(0xFF1C211C)
    val SurfaceContainerHighDark = Color(0xFF262B27)
    val SurfaceContainerHighestDark = Color(0xFF313631)
}
