package theme.color

import androidx.compose.ui.graphics.Color

object Haruki {
    val PrimaryLight = Color(0xFF725C0C)
    val OnPrimaryLight = Color(0xFFFFFFFF)
    val PrimaryContainerLight = Color(0xFFFFE086)
    val OnPrimaryContainerLight = Color(0xFF231B00)
    val SecondaryLight = Color(0xFF685E40)
    val OnSecondaryLight = Color(0xFFFFFFFF)
    val SecondaryContainerLight = Color(0xFFF1E1BB)
    val OnSecondaryContainerLight = Color(0xFF221B04)
    val TertiaryLight = Color(0xFF46664B)
    val OnTertiaryLight = Color(0xFFFFFFFF)
    val TertiaryContainerLight = Color(0xFFC7ECCA)
    val OnTertiaryContainerLight = Color(0xFF02210C)
    val ErrorLight = Color(0xFFBA1A1A)
    val OnErrorLight = Color(0xFFFFFFFF)
    val ErrorContainerLight = Color(0xFFFFDAD6)
    val OnErrorContainerLight = Color(0xFF410002)
    val BackgroundLight = Color(0xFFFFF8F0)
    val OnBackgroundLight = Color(0xFF1E1B13)
    val SurfaceLight = Color(0xFFFFF8F0)
    val OnSurfaceLight = Color(0xFF1E1B13)
    val SurfaceVariantLight = Color(0xFFEBE2CF)
    val OnSurfaceVariantLight = Color(0xFF4C4639)
    val OutlineLight = Color(0xFF7D7667)
    val OutlineVariantLight = Color(0xFFCEC6B4)
    val ScrimLight = Color(0xFF000000)
    val InverseSurfaceLight = Color(0xFF343027)
    val InverseOnSurfaceLight = Color(0xFFF8F0E2)
    val InversePrimaryLight = Color(0xFFE1C46D)
    val SurfaceDimLight = Color(0xFFE1D9CC)
    val SurfaceBrightLight = Color(0xFFFFF8F0)
    val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
    val SurfaceContainerLowLight = Color(0xFFFBF3E5)
    val SurfaceContainerLight = Color(0xFFF5EDDF)
    val SurfaceContainerHighLight = Color(0xFFEFE7DA)
    val SurfaceContainerHighestLight = Color(0xFFE9E2D4)

    val PrimaryDark = Color(0xFFE1C46D)
    val OnPrimaryDark = Color(0xFF3C2F00)
    val PrimaryContainerDark = Color(0xFF574500)
    val OnPrimaryContainerDark = Color(0xFFFFE086)
    val SecondaryDark = Color(0xFFD4C5A1)
    val OnSecondaryDark = Color(0xFF383016)
    val SecondaryContainerDark = Color(0xFF50462A)
    val OnSecondaryContainerDark = Color(0xFFF1E1BB)
    val TertiaryDark = Color(0xFFACCFAF)
    val OnTertiaryDark = Color(0xFF183720)
    val TertiaryContainerDark = Color(0xFF2F4E35)
    val OnTertiaryContainerDark = Color(0xFFC7ECCA)
    val ErrorDark = Color(0xFFFFB4AB)
    val OnErrorDark = Color(0xFF690005)
    val ErrorContainerDark = Color(0xFF93000A)
    val OnErrorContainerDark = Color(0xFFFFDAD6)
    val BackgroundDark = Color(0xFF16130B)
    val OnBackgroundDark = Color(0xFFE9E2D4)
    val SurfaceDark = Color(0xFF16130B)
    val OnSurfaceDark = Color(0xFFE9E2D4)
    val SurfaceVariantDark = Color(0xFF4C4639)
    val OnSurfaceVariantDark = Color(0xFFCEC6B4)
    val OutlineDark = Color(0xFF979080)
    val OutlineVariantDark = Color(0xFF4C4639)
    val ScrimDark = Color(0xFF000000)
    val InverseSurfaceDark = Color(0xFFE9E2D4)
    val InverseOnSurfaceDark = Color(0xFF343027)
    val InversePrimaryDark = Color(0xFF725C0C)
    val SurfaceDimDark = Color(0xFF16130B)
    val SurfaceBrightDark = Color(0xFF3D392F)
    val SurfaceContainerLowestDark = Color(0xFF110E07)
    val SurfaceContainerLowDark = Color(0xFF1E1B13)
    val SurfaceContainerDark = Color(0xFF231F17)
    val SurfaceContainerHighDark = Color(0xFF2D2A21)
    val SurfaceContainerHighestDark = Color(0xFF38342B)
}
