package theme.color

import androidx.compose.ui.graphics.Color

object Kanade {
    val PrimaryLight = Color(0xFF405F90)
    val OnPrimaryLight = Color(0xFFFFFFFF)
    val PrimaryContainerLight = Color(0xFFD6E3FF)
    val OnPrimaryContainerLight = Color(0xFF001B3E)
    val SecondaryLight = Color(0xFF565F71)
    val OnSecondaryLight = Color(0xFFFFFFFF)
    val SecondaryContainerLight = Color(0xFFDAE2F9)
    val OnSecondaryContainerLight = Color(0xFF131C2B)
    val TertiaryLight = Color(0xFF6F5575)
    val OnTertiaryLight = Color(0xFFFFFFFF)
    val TertiaryContainerLight = Color(0xFFF9D8FD)
    val OnTertiaryContainerLight = Color(0xFF28132E)
    val ErrorLight = Color(0xFFBA1A1A)
    val OnErrorLight = Color(0xFFFFFFFF)
    val ErrorContainerLight = Color(0xFFFFDAD6)
    val OnErrorContainerLight = Color(0xFF410002)
    val BackgroundLight = Color(0xFFF9F9FF)
    val OnBackgroundLight = Color(0xFF191C20)
    val SurfaceLight = Color(0xFFF9F9FF)
    val OnSurfaceLight = Color(0xFF191C20)
    val SurfaceVariantLight = Color(0xFFE0E2EC)
    val OnSurfaceVariantLight = Color(0xFF44474E)
    val OutlineLight = Color(0xFF74777F)
    val OutlineVariantLight = Color(0xFFC4C6D0)
    val ScrimLight = Color(0xFF000000)
    val InverseSurfaceLight = Color(0xFF2E3036)
    val InverseOnSurfaceLight = Color(0xFFF0F0F7)
    val InversePrimaryLight = Color(0xFFA9C7FF)
    val SurfaceDimLight = Color(0xFFD9D9E0)
    val SurfaceBrightLight = Color(0xFFF9F9FF)
    val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
    val SurfaceContainerLowLight = Color(0xFFF3F3FA)
    val SurfaceContainerLight = Color(0xFFEDEDF4)
    val SurfaceContainerHighLight = Color(0xFFE7E8EE)
    val SurfaceContainerHighestLight = Color(0xFFE2E2E9)

    val PrimaryDark = Color(0xFFA9C7FF)
    val OnPrimaryDark = Color(0xFF09305F)
    val PrimaryContainerDark = Color(0xFF274777)
    val OnPrimaryContainerDark = Color(0xFFD6E3FF)
    val SecondaryDark = Color(0xFFBEC7DC)
    val OnSecondaryDark = Color(0xFF283141)
    val SecondaryContainerDark = Color(0xFF3E4759)
    val OnSecondaryContainerDark = Color(0xFFDAE2F9)
    val TertiaryDark = Color(0xFFDCBCE1)
    val OnTertiaryDark = Color(0xFF3F2845)
    val TertiaryContainerDark = Color(0xFF563E5C)
    val OnTertiaryContainerDark = Color(0xFFF9D8FD)
    val ErrorDark = Color(0xFFFFB4AB)
    val OnErrorDark = Color(0xFF690005)
    val ErrorContainerDark = Color(0xFF93000A)
    val OnErrorContainerDark = Color(0xFFFFDAD6)
    val BackgroundDark = Color(0xFF111318)
    val OnBackgroundDark = Color(0xFFE2E2E9)
    val SurfaceDark = Color(0xFF111318)
    val OnSurfaceDark = Color(0xFFE2E2E9)
    val SurfaceVariantDark = Color(0xFF44474E)
    val OnSurfaceVariantDark = Color(0xFFC4C6D0)
    val OutlineDark = Color(0xFF8E9099)
    val OutlineVariantDark = Color(0xFF44474E)
    val ScrimDark = Color(0xFF000000)
    val InverseSurfaceDark = Color(0xFFE2E2E9)
    val InverseOnSurfaceDark = Color(0xFF2E3036)
    val InversePrimaryDark = Color(0xFF405F90)
    val SurfaceDimDark = Color(0xFF111318)
    val SurfaceBrightDark = Color(0xFF37393E)
    val SurfaceContainerLowestDark = Color(0xFF0C0E13)
    val SurfaceContainerLowDark = Color(0xFF191C20)
    val SurfaceContainerDark = Color(0xFF1D2024)
    val SurfaceContainerHighDark = Color(0xFF282A2F)
    val SurfaceContainerHighestDark = Color(0xFF33353A)
}
