package theme.color

import androidx.compose.ui.graphics.Color

object Kanon {
    val PrimaryLight = Color(0xFF835415)
    val OnPrimaryLight = Color(0xFFFFFFFF)
    val PrimaryContainerLight = Color(0xFFFFDDBA)
    val OnPrimaryContainerLight = Color(0xFF673D00)
    val SecondaryLight = Color(0xFF715A41)
    val OnSecondaryLight = Color(0xFFFFFFFF)
    val SecondaryContainerLight = Color(0xFFFDDDBD)
    val OnSecondaryContainerLight = Color(0xFF58432B)
    val TertiaryLight = Color(0xFF55633C)
    val OnTertiaryLight = Color(0xFFFFFFFF)
    val TertiaryContainerLight = Color(0xFFD9E9B7)
    val OnTertiaryContainerLight = Color(0xFF3E4B26)
    val ErrorLight = Color(0xFFBA1A1A)
    val OnErrorLight = Color(0xFFFFFFFF)
    val ErrorContainerLight = Color(0xFFFFDAD6)
    val OnErrorContainerLight = Color(0xFF93000A)
    val BackgroundLight = Color(0xFFFFF8F4)
    val OnBackgroundLight = Color(0xFF211A13)
    val SurfaceLight = Color(0xFFFFF8F4)
    val OnSurfaceLight = Color(0xFF211A13)
    val SurfaceVariantLight = Color(0xFFF1DFD0)
    val OnSurfaceVariantLight = Color(0xFF50453A)
    val OutlineLight = Color(0xFF827568)
    val OutlineVariantLight = Color(0xFFD4C4B5)
    val ScrimLight = Color(0xFF000000)
    val InverseSurfaceLight = Color(0xFF372F27)
    val InverseOnSurfaceLight = Color(0xFFFDEEE3)
    val InversePrimaryLight = Color(0xFFF9BA72)
    val SurfaceDimLight = Color(0xFFE5D8CC)
    val SurfaceBrightLight = Color(0xFFFFF8F4)
    val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
    val SurfaceContainerLowLight = Color(0xFFFFF1E6)
    val SurfaceContainerLight = Color(0xFFFAEBE0)
    val SurfaceContainerHighLight = Color(0xFFF4E6DA)
    val SurfaceContainerHighestLight = Color(0xFFEEE0D5)

    val PrimaryDark = Color(0xFFF9BA72)
    val OnPrimaryDark = Color(0xFF482A00)
    val PrimaryContainerDark = Color(0xFF673D00)
    val OnPrimaryContainerDark = Color(0xFFFFDDBA)
    val SecondaryDark = Color(0xFFE0C1A3)
    val OnSecondaryDark = Color(0xFF3F2D17)
    val SecondaryContainerDark = Color(0xFF58432B)
    val OnSecondaryContainerDark = Color(0xFFFDDDBD)
    val TertiaryDark = Color(0xFFBDCD9D)
    val OnTertiaryDark = Color(0xFF283412)
    val TertiaryContainerDark = Color(0xFF3E4B26)
    val OnTertiaryContainerDark = Color(0xFFD9E9B7)
    val ErrorDark = Color(0xFFFFB4AB)
    val OnErrorDark = Color(0xFF690005)
    val ErrorContainerDark = Color(0xFF93000A)
    val OnErrorContainerDark = Color(0xFFFFDAD6)
    val BackgroundDark = Color(0xFF18120C)
    val OnBackgroundDark = Color(0xFFEEE0D5)
    val SurfaceDark = Color(0xFF18120C)
    val OnSurfaceDark = Color(0xFFEEE0D5)
    val SurfaceVariantDark = Color(0xFF50453A)
    val OnSurfaceVariantDark = Color(0xFFD4C4B5)
    val OutlineDark = Color(0xFF9D8E81)
    val OutlineVariantDark = Color(0xFF50453A)
    val ScrimDark = Color(0xFF000000)
    val InverseSurfaceDark = Color(0xFFEEE0D5)
    val InverseOnSurfaceDark = Color(0xFF372F27)
    val InversePrimaryDark = Color(0xFF835415)
    val SurfaceDimDark = Color(0xFF18120C)
    val SurfaceBrightDark = Color(0xFF403830)
    val SurfaceContainerLowestDark = Color(0xFF130D07)
    val SurfaceContainerLowDark = Color(0xFF211A13)
    val SurfaceContainerDark = Color(0xFF251E17)
    val SurfaceContainerHighDark = Color(0xFF302921)
    val SurfaceContainerHighestDark = Color(0xFF3B332C)
}
