package theme.color

import androidx.compose.ui.graphics.Color

object Kotlin {
    val PrimaryLight = Color(0xFF63568F)
    val OnPrimaryLight = Color(0xFFFFFFFF)
    val PrimaryContainerLight = Color(0xFFE8DEFF)
    val OnPrimaryContainerLight = Color(0xFF1F1048)
    val SecondaryLight = Color(0xFF615B71)
    val OnSecondaryLight = Color(0xFFFFFFFF)
    val SecondaryContainerLight = Color(0xFFE7DEF8)
    val OnSecondaryContainerLight = Color(0xFF1D192B)
    val TertiaryLight = Color(0xFF7D5261)
    val OnTertiaryLight = Color(0xFFFFFFFF)
    val TertiaryContainerLight = Color(0xFFFFD9E4)
    val OnTertiaryContainerLight = Color(0xFF31111E)
    val ErrorLight = Color(0xFFBA1A1A)
    val OnErrorLight = Color(0xFFFFFFFF)
    val ErrorContainerLight = Color(0xFFFFDAD6)
    val OnErrorContainerLight = Color(0xFF410002)
    val BackgroundLight = Color(0xFFFDF7FF)
    val OnBackgroundLight = Color(0xFF1C1B20)
    val SurfaceLight = Color(0xFFFDF7FF)
    val OnSurfaceLight = Color(0xFF1C1B20)
    val SurfaceVariantLight = Color(0xFFE6E0EC)
    val OnSurfaceVariantLight = Color(0xFF48454E)
    val OutlineLight = Color(0xFF79757F)
    val OutlineVariantLight = Color(0xFFCAC4CF)
    val ScrimLight = Color(0xFF000000)
    val InverseSurfaceLight = Color(0xFF312F35)
    val InverseOnSurfaceLight = Color(0xFFF4EFF7)
    val InversePrimaryLight = Color(0xFFCDBDFF)
    val SurfaceDimLight = Color(0xFFDDD8E0)
    val SurfaceBrightLight = Color(0xFFFDF7FF)
    val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
    val SurfaceContainerLowLight = Color(0xFFF7F2FA)
    val SurfaceContainerLight = Color(0xFFF2ECF4)
    val SurfaceContainerHighLight = Color(0xFFECE6EE)
    val SurfaceContainerHighestLight = Color(0xFFE6E1E9)

    val PrimaryDark = Color(0xFFCDBDFF)
    val OnPrimaryDark = Color(0xFF34275E)
    val PrimaryContainerDark = Color(0xFF4B3E76)
    val OnPrimaryContainerDark = Color(0xFFE8DEFF)
    val SecondaryDark = Color(0xFFCBC3DC)
    val OnSecondaryDark = Color(0xFF322E41)
    val SecondaryContainerDark = Color(0xFF494458)
    val OnSecondaryContainerDark = Color(0xFFE7DEF8)
    val TertiaryDark = Color(0xFFEEB8CA)
    val OnTertiaryDark = Color(0xFF492533)
    val TertiaryContainerDark = Color(0xFF633B4A)
    val OnTertiaryContainerDark = Color(0xFFFFD9E4)
    val ErrorDark = Color(0xFFFFB4AB)
    val OnErrorDark = Color(0xFF690005)
    val ErrorContainerDark = Color(0xFF93000A)
    val OnErrorContainerDark = Color(0xFFFFDAD6)
    val BackgroundDark = Color(0xFF141318)
    val OnBackgroundDark = Color(0xFFE6E1E9)
    val SurfaceDark = Color(0xFF141318)
    val OnSurfaceDark = Color(0xFFE6E1E9)
    val SurfaceVariantDark = Color(0xFF48454E)
    val OnSurfaceVariantDark = Color(0xFFCAC4CF)
    val OutlineDark = Color(0xFF938F99)
    val OutlineVariantDark = Color(0xFF48454E)
    val ScrimDark = Color(0xFF000000)
    val InverseSurfaceDark = Color(0xFFE6E1E9)
    val InverseOnSurfaceDark = Color(0xFF312F35)
    val InversePrimaryDark = Color(0xFF63568F)
    val SurfaceDimDark = Color(0xFF141318)
    val SurfaceBrightDark = Color(0xFF3A383E)
    val SurfaceContainerLowestDark = Color(0xFF0F0D13)
    val SurfaceContainerLowDark = Color(0xFF1C1B20)
    val SurfaceContainerDark = Color(0xFF201F24)
    val SurfaceContainerHighDark = Color(0xFF2B292F)
    val SurfaceContainerHighestDark = Color(0xFF36343A)
}
