package theme.color

import androidx.compose.ui.graphics.Color

object Madoka {
    val PrimaryLight = Color(0xFF8F4A4F)
    val OnPrimaryLight = Color(0xFFFFFFFF)
    val PrimaryContainerLight = Color(0xFFFFDADA)
    val OnPrimaryContainerLight = Color(0xFF3B0810)
    val SecondaryLight = Color(0xFF765657)
    val OnSecondaryLight = Color(0xFFFFFFFF)
    val SecondaryContainerLight = Color(0xFFFFDADA)
    val OnSecondaryContainerLight = Color(0xFF2C1516)
    val TertiaryLight = Color(0xFF76592F)
    val OnTertiaryLight = Color(0xFFFFFFFF)
    val TertiaryContainerLight = Color(0xFFFFDDB2)
    val OnTertiaryContainerLight = Color(0xFF291800)
    val ErrorLight = Color(0xFFBA1A1A)
    val OnErrorLight = Color(0xFFFFFFFF)
    val ErrorContainerLight = Color(0xFFFFDAD6)
    val OnErrorContainerLight = Color(0xFF410002)
    val BackgroundLight = Color(0xFFFFF8F7)
    val OnBackgroundLight = Color(0xFF22191A)
    val SurfaceLight = Color(0xFFFFF8F7)
    val OnSurfaceLight = Color(0xFF22191A)
    val SurfaceVariantLight = Color(0xFFF4DDDD)
    val OnSurfaceVariantLight = Color(0xFF524343)
    val OutlineLight = Color(0xFF857373)
    val OutlineVariantLight = Color(0xFFD7C1C2)
    val ScrimLight = Color(0xFF000000)
    val InverseSurfaceLight = Color(0xFF382E2E)
    val InverseOnSurfaceLight = Color(0xFFFFEDEC)
    val InversePrimaryLight = Color(0xFFFFB3B6)
    val SurfaceDimLight = Color(0xFFE7D6D6)
    val SurfaceBrightLight = Color(0xFFFFF8F7)
    val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
    val SurfaceContainerLowLight = Color(0xFFFFF0F0)
    val SurfaceContainerLight = Color(0xFFFCEAE9)
    val SurfaceContainerHighLight = Color(0xFFF6E4E4)
    val SurfaceContainerHighestLight = Color(0xFFF0DEDE)

    val PrimaryDark = Color(0xFFFFB3B6)
    val OnPrimaryDark = Color(0xFF561D23)
    val PrimaryContainerDark = Color(0xFF723338)
    val OnPrimaryContainerDark = Color(0xFFFFDADA)
    val SecondaryDark = Color(0xFFE6BDBE)
    val OnSecondaryDark = Color(0xFF44292B)
    val SecondaryContainerDark = Color(0xFF5D3F40)
    val OnSecondaryContainerDark = Color(0xFFFFDADA)
    val TertiaryDark = Color(0xFFE7C08D)
    val OnTertiaryDark = Color(0xFF432C06)
    val TertiaryContainerDark = Color(0xFF5C421A)
    val OnTertiaryContainerDark = Color(0xFFFFDDB2)
    val ErrorDark = Color(0xFFFFB4AB)
    val OnErrorDark = Color(0xFF690005)
    val ErrorContainerDark = Color(0xFF93000A)
    val OnErrorContainerDark = Color(0xFFFFDAD6)
    val BackgroundDark = Color(0xFF1A1111)
    val OnBackgroundDark = Color(0xFFF0DEDE)
    val SurfaceDark = Color(0xFF1A1111)
    val OnSurfaceDark = Color(0xFFF0DEDE)
    val SurfaceVariantDark = Color(0xFF524343)
    val OnSurfaceVariantDark = Color(0xFFD7C1C2)
    val OutlineDark = Color(0xFF9F8C8C)
    val OutlineVariantDark = Color(0xFF524343)
    val ScrimDark = Color(0xFF000000)
    val InverseSurfaceDark = Color(0xFFF0DEDE)
    val InverseOnSurfaceDark = Color(0xFF382E2E)
    val InversePrimaryDark = Color(0xFF8F4A4F)
    val SurfaceDimDark = Color(0xFF1A1111)
    val SurfaceBrightDark = Color(0xFF413737)
    val SurfaceContainerLowestDark = Color(0xFF140C0C)
    val SurfaceContainerLowDark = Color(0xFF22191A)
    val SurfaceContainerDark = Color(0xFF271D1E)
    val SurfaceContainerHighDark = Color(0xFF322828)
    val SurfaceContainerHighestDark = Color(0xFF3D3232)
}
