package theme.color

import androidx.compose.ui.graphics.Color

object Mizuki {
    val PrimaryLight = Color(0xFF35618E)
    val OnPrimaryLight = Color(0xFFFFFFFF)
    val PrimaryContainerLight = Color(0xFFD1E4FF)
    val OnPrimaryContainerLight = Color(0xFF001D35)
    val SecondaryLight = Color(0xFF535F70)
    val OnSecondaryLight = Color(0xFFFFFFFF)
    val SecondaryContainerLight = Color(0xFFD6E4F7)
    val OnSecondaryContainerLight = Color(0xFF0F1C2B)
    val TertiaryLight = Color(0xFF6A5778)
    val OnTertiaryLight = Color(0xFFFFFFFF)
    val TertiaryContainerLight = Color(0xFFF2DAFF)
    val OnTertiaryContainerLight = Color(0xFF251432)
    val ErrorLight = Color(0xFFBA1A1A)
    val OnErrorLight = Color(0xFFFFFFFF)
    val ErrorContainerLight = Color(0xFFFFDAD6)
    val OnErrorContainerLight = Color(0xFF410002)
    val BackgroundLight = Color(0xFFF8F9FF)
    val OnBackgroundLight = Color(0xFF191C20)
    val SurfaceLight = Color(0xFFF8F9FF)
    val OnSurfaceLight = Color(0xFF191C20)
    val SurfaceVariantLight = Color(0xFFDFE2EB)
    val OnSurfaceVariantLight = Color(0xFF42474E)
    val OutlineLight = Color(0xFF73777F)
    val OutlineVariantLight = Color(0xFFC3C7CF)
    val ScrimLight = Color(0xFF000000)
    val InverseSurfaceLight = Color(0xFF2E3135)
    val InverseOnSurfaceLight = Color(0xFFEFF0F7)
    val InversePrimaryLight = Color(0xFF9FCAFC)
    val SurfaceDimLight = Color(0xFFD8DAE0)
    val SurfaceBrightLight = Color(0xFFF8F9FF)
    val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
    val SurfaceContainerLowLight = Color(0xFFF2F3F9)
    val SurfaceContainerLight = Color(0xFFECEEF4)
    val SurfaceContainerHighLight = Color(0xFFE6E8EE)
    val SurfaceContainerHighestLight = Color(0xFFE1E2E8)

    val PrimaryDark = Color(0xFF9FCAFC)
    val OnPrimaryDark = Color(0xFF003257)
    val PrimaryContainerDark = Color(0xFF174974)
    val OnPrimaryContainerDark = Color(0xFFD1E4FF)
    val SecondaryDark = Color(0xFFBAC8DB)
    val OnSecondaryDark = Color(0xFF253140)
    val SecondaryContainerDark = Color(0xFF3B4858)
    val OnSecondaryContainerDark = Color(0xFFD6E4F7)
    val TertiaryDark = Color(0xFFD6BEE5)
    val OnTertiaryDark = Color(0xFF3A2948)
    val TertiaryContainerDark = Color(0xFF524060)
    val OnTertiaryContainerDark = Color(0xFFF2DAFF)
    val ErrorDark = Color(0xFFFFB4AB)
    val OnErrorDark = Color(0xFF690005)
    val ErrorContainerDark = Color(0xFF93000A)
    val OnErrorContainerDark = Color(0xFFFFDAD6)
    val BackgroundDark = Color(0xFF101418)
    val OnBackgroundDark = Color(0xFFE1E2E8)
    val SurfaceDark = Color(0xFF101418)
    val OnSurfaceDark = Color(0xFFE1E2E8)
    val SurfaceVariantDark = Color(0xFF42474E)
    val OnSurfaceVariantDark = Color(0xFFC3C7CF)
    val OutlineDark = Color(0xFF8D9199)
    val OutlineVariantDark = Color(0xFF42474E)
    val ScrimDark = Color(0xFF000000)
    val InverseSurfaceDark = Color(0xFFE1E2E8)
    val InverseOnSurfaceDark = Color(0xFF2E3135)
    val InversePrimaryDark = Color(0xFF35618E)
    val SurfaceDimDark = Color(0xFF101418)
    val SurfaceBrightDark = Color(0xFF36393E)
    val SurfaceContainerLowestDark = Color(0xFF0B0E13)
    val SurfaceContainerLowDark = Color(0xFF191C20)
    val SurfaceContainerDark = Color(0xFF1D2024)
    val SurfaceContainerHighDark = Color(0xFF272A2F)
    val SurfaceContainerHighestDark = Color(0xFF32353A)
}
