package theme.color

import androidx.compose.ui.graphics.Color

object Rails {
    val PrimaryLight = Color(0xFF904B40)
    val OnPrimaryLight = Color(0xFFFFFFFF)
    val PrimaryContainerLight = Color(0xFFFFDAD4)
    val OnPrimaryContainerLight = Color(0xFF3A0905)
    val SecondaryLight = Color(0xFF775651)
    val OnSecondaryLight = Color(0xFFFFFFFF)
    val SecondaryContainerLight = Color(0xFFFFDAD4)
    val OnSecondaryContainerLight = Color(0xFF2C1512)
    val TertiaryLight = Color(0xFF705C2E)
    val OnTertiaryLight = Color(0xFFFFFFFF)
    val TertiaryContainerLight = Color(0xFFFBDFA6)
    val OnTertiaryContainerLight = Color(0xFF251A00)
    val ErrorLight = Color(0xFFBA1A1A)
    val OnErrorLight = Color(0xFFFFFFFF)
    val ErrorContainerLight = Color(0xFFFFDAD6)
    val OnErrorContainerLight = Color(0xFF410002)
    val BackgroundLight = Color(0xFFFFF8F6)
    val OnBackgroundLight = Color(0xFF231918)
    val SurfaceLight = Color(0xFFFFF8F6)
    val OnSurfaceLight = Color(0xFF231918)
    val SurfaceVariantLight = Color(0xFFF5DDDA)
    val OnSurfaceVariantLight = Color(0xFF534341)
    val OutlineLight = Color(0xFF857370)
    val OutlineVariantLight = Color(0xFFD8C2BE)
    val ScrimLight = Color(0xFF000000)
    val InverseSurfaceLight = Color(0xFF392E2C)
    val InverseOnSurfaceLight = Color(0xFFFFEDEA)
    val InversePrimaryLight = Color(0xFFFFB4A8)
    val SurfaceDimLight = Color(0xFFE8D6D3)
    val SurfaceBrightLight = Color(0xFFFFF8F6)
    val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
    val SurfaceContainerLowLight = Color(0xFFFFF0EE)
    val SurfaceContainerLight = Color(0xFFFCEAE7)
    val SurfaceContainerHighLight = Color(0xFFF7E4E1)
    val SurfaceContainerHighestLight = Color(0xFFF1DFDC)

    val PrimaryDark = Color(0xFFFFB4A8)
    val OnPrimaryDark = Color(0xFF561E17)
    val PrimaryContainerDark = Color(0xFF73342B)
    val OnPrimaryContainerDark = Color(0xFFFFDAD4)
    val SecondaryDark = Color(0xFFE7BDB6)
    val OnSecondaryDark = Color(0xFF442925)
    val SecondaryContainerDark = Color(0xFF5D3F3B)
    val OnSecondaryContainerDark = Color(0xFFFFDAD4)
    val TertiaryDark = Color(0xFFDEC48C)
    val OnTertiaryDark = Color(0xFF3E2E04)
    val TertiaryContainerDark = Color(0xFF564419)
    val OnTertiaryContainerDark = Color(0xFFFBDFA6)
    val ErrorDark = Color(0xFFFFB4AB)
    val OnErrorDark = Color(0xFF690005)
    val ErrorContainerDark = Color(0xFF93000A)
    val OnErrorContainerDark = Color(0xFFFFDAD6)
    val BackgroundDark = Color(0xFF1A1110)
    val OnBackgroundDark = Color(0xFFF1DFDC)
    val SurfaceDark = Color(0xFF1A1110)
    val OnSurfaceDark = Color(0xFFF1DFDC)
    val SurfaceVariantDark = Color(0xFF534341)
    val OnSurfaceVariantDark = Color(0xFFD8C2BE)
    val OutlineDark = Color(0xFFA08C89)
    val OutlineVariantDark = Color(0xFF534341)
    val ScrimDark = Color(0xFF000000)
    val InverseSurfaceDark = Color(0xFFF1DFDC)
    val InverseOnSurfaceDark = Color(0xFF392E2C)
    val InversePrimaryDark = Color(0xFF904B40)
    val SurfaceDimDark = Color(0xFF1A1110)
    val SurfaceBrightDark = Color(0xFF423735)
    val SurfaceContainerLowestDark = Color(0xFF140C0B)
    val SurfaceContainerLowDark = Color(0xFF231918)
    val SurfaceContainerDark = Color(0xFF271D1C)
    val SurfaceContainerHighDark = Color(0xFF322826)
    val SurfaceContainerHighestDark = Color(0xFF3D3231)
}
