package theme.color

import androidx.compose.ui.graphics.Color

object React {
    val PrimaryLight = Color(0xFF00677C)
    val OnPrimaryLight = Color(0xFFFFFFFF)
    val PrimaryContainerLight = Color(0xFFB1ECFF)
    val OnPrimaryContainerLight = Color(0xFF001F27)
    val SecondaryLight = Color(0xFF4B6269)
    val OnSecondaryLight = Color(0xFFFFFFFF)
    val SecondaryContainerLight = Color(0xFFCEE7EF)
    val OnSecondaryContainerLight = Color(0xFF061E25)
    val TertiaryLight = Color(0xFF585C7E)
    val OnTertiaryLight = Color(0xFFFFFFFF)
    val TertiaryContainerLight = Color(0xFFDFE0FF)
    val OnTertiaryContainerLight = Color(0xFF151937)
    val ErrorLight = Color(0xFFBA1A1A)
    val OnErrorLight = Color(0xFFFFFFFF)
    val ErrorContainerLight = Color(0xFFFFDAD6)
    val OnErrorContainerLight = Color(0xFF410002)
    val BackgroundLight = Color(0xFFF5FAFD)
    val OnBackgroundLight = Color(0xFF171C1E)
    val SurfaceLight = Color(0xFFF5FAFD)
    val OnSurfaceLight = Color(0xFF171C1E)
    val SurfaceVariantLight = Color(0xFFDBE4E8)
    val OnSurfaceVariantLight = Color(0xFF40484B)
    val OutlineLight = Color(0xFF70787C)
    val OutlineVariantLight = Color(0xFFBFC8CB)
    val ScrimLight = Color(0xFF000000)
    val InverseSurfaceLight = Color(0xFF2C3133)
    val InverseOnSurfaceLight = Color(0xFFECF1F4)
    val InversePrimaryLight = Color(0xFF86D1E9)
    val SurfaceDimLight = Color(0xFFD6DBDD)
    val SurfaceBrightLight = Color(0xFFF5FAFD)
    val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
    val SurfaceContainerLowLight = Color(0xFFEFF4F7)
    val SurfaceContainerLight = Color(0xFFEAEFF1)
    val SurfaceContainerHighLight = Color(0xFFE4E9EB)
    val SurfaceContainerHighestLight = Color(0xFFDEE3E6)

    val PrimaryDark = Color(0xFF86D1E9)
    val OnPrimaryDark = Color(0xFF003641)
    val PrimaryContainerDark = Color(0xFF004E5E)
    val OnPrimaryContainerDark = Color(0xFFB1ECFF)
    val SecondaryDark = Color(0xFFB2CAD3)
    val OnSecondaryDark = Color(0xFF1D343A)
    val SecondaryContainerDark = Color(0xFF344A51)
    val OnSecondaryContainerDark = Color(0xFFCEE7EF)
    val TertiaryDark = Color(0xFFC0C4EB)
    val OnTertiaryDark = Color(0xFF2A2E4D)
    val TertiaryContainerDark = Color(0xFF404565)
    val OnTertiaryContainerDark = Color(0xFFDFE0FF)
    val ErrorDark = Color(0xFFFFB4AB)
    val OnErrorDark = Color(0xFF690005)
    val ErrorContainerDark = Color(0xFF93000A)
    val OnErrorContainerDark = Color(0xFFFFDAD6)
    val BackgroundDark = Color(0xFF0F1416)
    val OnBackgroundDark = Color(0xFFDEE3E6)
    val SurfaceDark = Color(0xFF0F1416)
    val OnSurfaceDark = Color(0xFFDEE3E6)
    val SurfaceVariantDark = Color(0xFF40484B)
    val OnSurfaceVariantDark = Color(0xFFBFC8CB)
    val OutlineDark = Color(0xFF899296)
    val OutlineVariantDark = Color(0xFF40484B)
    val ScrimDark = Color(0xFF000000)
    val InverseSurfaceDark = Color(0xFFDEE3E6)
    val InverseOnSurfaceDark = Color(0xFF2C3133)
    val InversePrimaryDark = Color(0xFF00677C)
    val SurfaceDimDark = Color(0xFF0F1416)
    val SurfaceBrightDark = Color(0xFF343A3C)
    val SurfaceContainerLowestDark = Color(0xFF090F11)
    val SurfaceContainerLowDark = Color(0xFF171C1E)
    val SurfaceContainerDark = Color(0xFF1B2022)
    val SurfaceContainerHighDark = Color(0xFF252B2D)
    val SurfaceContainerHighestDark = Color(0xFF303638)
}
