package theme.color

import androidx.compose.ui.graphics.Color

object Sayaka {
    val PrimaryLight = Color(0xFF3C6090)
    val OnPrimaryLight = Color(0xFFFFFFFF)
    val PrimaryContainerLight = Color(0xFFD4E3FF)
    val OnPrimaryContainerLight = Color(0xFF001C3A)
    val SecondaryLight = Color(0xFF545F71)
    val OnSecondaryLight = Color(0xFFFFFFFF)
    val SecondaryContainerLight = Color(0xFFD8E3F8)
    val OnSecondaryContainerLight = Color(0xFF111C2B)
    val TertiaryLight = Color(0xFF6D5676)
    val OnTertiaryLight = Color(0xFFFFFFFF)
    val TertiaryContainerLight = Color(0xFFF7D9FF)
    val OnTertiaryContainerLight = Color(0xFF271430)
    val ErrorLight = Color(0xFFBA1A1A)
    val OnErrorLight = Color(0xFFFFFFFF)
    val ErrorContainerLight = Color(0xFFFFDAD6)
    val OnErrorContainerLight = Color(0xFF410002)
    val BackgroundLight = Color(0xFFF9F9FF)
    val OnBackgroundLight = Color(0xFF191C20)
    val SurfaceLight = Color(0xFFF9F9FF)
    val OnSurfaceLight = Color(0xFF191C20)
    val SurfaceVariantLight = Color(0xFFE0E2EC)
    val OnSurfaceVariantLight = Color(0xFF43474E)
    val OutlineLight = Color(0xFF74777F)
    val OutlineVariantLight = Color(0xFFC3C6CF)
    val ScrimLight = Color(0xFF000000)
    val InverseSurfaceLight = Color(0xFF2E3035)
    val InverseOnSurfaceLight = Color(0xFFF0F0F7)
    val InversePrimaryLight = Color(0xFFA5C8FF)
    val SurfaceDimLight = Color(0xFFD9DAE0)
    val SurfaceBrightLight = Color(0xFFF9F9FF)
    val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
    val SurfaceContainerLowLight = Color(0xFFF2F3FA)
    val SurfaceContainerLight = Color(0xFFEDEDF4)
    val SurfaceContainerHighLight = Color(0xFFE7E8EE)
    val SurfaceContainerHighestLight = Color(0xFFE1E2E9)

    val PrimaryDark = Color(0xFFA5C8FF)
    val OnPrimaryDark = Color(0xFF00315E)
    val PrimaryContainerDark = Color(0xFF214876)
    val OnPrimaryContainerDark = Color(0xFFD4E3FF)
    val SecondaryDark = Color(0xFFBCC7DC)
    val OnSecondaryDark = Color(0xFF263141)
    val SecondaryContainerDark = Color(0xFF3D4758)
    val OnSecondaryContainerDark = Color(0xFFD8E3F8)
    val TertiaryDark = Color(0xFFDABDE2)
    val OnTertiaryDark = Color(0xFF3D2946)
    val TertiaryContainerDark = Color(0xFF553F5E)
    val OnTertiaryContainerDark = Color(0xFFF7D9FF)
    val ErrorDark = Color(0xFFFFB4AB)
    val OnErrorDark = Color(0xFF690005)
    val ErrorContainerDark = Color(0xFF93000A)
    val OnErrorContainerDark = Color(0xFFFFDAD6)
    val BackgroundDark = Color(0xFF111318)
    val OnBackgroundDark = Color(0xFFE1E2E9)
    val SurfaceDark = Color(0xFF111318)
    val OnSurfaceDark = Color(0xFFE1E2E9)
    val SurfaceVariantDark = Color(0xFF43474E)
    val OnSurfaceVariantDark = Color(0xFFC3C6CF)
    val OutlineDark = Color(0xFF8D9199)
    val OutlineVariantDark = Color(0xFF43474E)
    val ScrimDark = Color(0xFF000000)
    val InverseSurfaceDark = Color(0xFFE1E2E9)
    val InverseOnSurfaceDark = Color(0xFF2E3035)
    val InversePrimaryDark = Color(0xFF3C6090)
    val SurfaceDimDark = Color(0xFF111318)
    val SurfaceBrightDark = Color(0xFF37393E)
    val SurfaceContainerLowestDark = Color(0xFF0C0E13)
    val SurfaceContainerLowDark = Color(0xFF191C20)
    val SurfaceContainerDark = Color(0xFF1D2024)
    val SurfaceContainerHighDark = Color(0xFF282A2F)
    val SurfaceContainerHighestDark = Color(0xFF32353A)
}
