package theme.color

import androidx.compose.ui.graphics.Color

object Temari {
    val PrimaryLight = Color(0xFF206487)
    val OnPrimaryLight = Color(0xFFFFFFFF)
    val PrimaryContainerLight = Color(0xFFC6E7FF)
    val OnPrimaryContainerLight = Color(0xFF001E2D)
    val SecondaryLight = Color(0xFF4F616E)
    val OnSecondaryLight = Color(0xFFFFFFFF)
    val SecondaryContainerLight = Color(0xFFD2E5F4)
    val OnSecondaryContainerLight = Color(0xFF0A1D28)
    val TertiaryLight = Color(0xFF62597C)
    val OnTertiaryLight = Color(0xFFFFFFFF)
    val TertiaryContainerLight = Color(0xFFE8DDFF)
    val OnTertiaryContainerLight = Color(0xFF1E1635)
    val ErrorLight = Color(0xFFBA1A1A)
    val OnErrorLight = Color(0xFFFFFFFF)
    val ErrorContainerLight = Color(0xFFFFDAD6)
    val OnErrorContainerLight = Color(0xFF410002)
    val BackgroundLight = Color(0xFFF6FAFE)
    val OnBackgroundLight = Color(0xFF181C1F)
    val SurfaceLight = Color(0xFFF6FAFE)
    val OnSurfaceLight = Color(0xFF181C1F)
    val SurfaceVariantLight = Color(0xFFDDE3EA)
    val OnSurfaceVariantLight = Color(0xFF41484D)
    val OutlineLight = Color(0xFF71787E)
    val OutlineVariantLight = Color(0xFFC1C7CE)
    val ScrimLight = Color(0xFF000000)
    val InverseSurfaceLight = Color(0xFF2C3135)
    val InverseOnSurfaceLight = Color(0xFFEEF1F6)
    val InversePrimaryLight = Color(0xFF92CEF5)
    val SurfaceDimLight = Color(0xFFD7DADF)
    val SurfaceBrightLight = Color(0xFFF6FAFE)
    val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
    val SurfaceContainerLowLight = Color(0xFFF0F4F8)
    val SurfaceContainerLight = Color(0xFFEBEEF3)
    val SurfaceContainerHighLight = Color(0xFFE5E8ED)
    val SurfaceContainerHighestLight = Color(0xFFDFE3E7)

    val PrimaryDark = Color(0xFF92CEF5)
    val OnPrimaryDark = Color(0xFF00344B)
    val PrimaryContainerDark = Color(0xFF004C6B)
    val OnPrimaryContainerDark = Color(0xFFC6E7FF)
    val SecondaryDark = Color(0xFFB6C9D8)
    val OnSecondaryDark = Color(0xFF21323E)
    val SecondaryContainerDark = Color(0xFF374955)
    val OnSecondaryContainerDark = Color(0xFFD2E5F4)
    val TertiaryDark = Color(0xFFCCC1E9)
    val OnTertiaryDark = Color(0xFF332C4B)
    val TertiaryContainerDark = Color(0xFF4A4263)
    val OnTertiaryContainerDark = Color(0xFFE8DDFF)
    val ErrorDark = Color(0xFFFFB4AB)
    val OnErrorDark = Color(0xFF690005)
    val ErrorContainerDark = Color(0xFF93000A)
    val OnErrorContainerDark = Color(0xFFFFDAD6)
    val BackgroundDark = Color(0xFF0F1417)
    val OnBackgroundDark = Color(0xFFDFE3E7)
    val SurfaceDark = Color(0xFF0F1417)
    val OnSurfaceDark = Color(0xFFDFE3E7)
    val SurfaceVariantDark = Color(0xFF41484D)
    val OnSurfaceVariantDark = Color(0xFFC1C7CE)
    val OutlineDark = Color(0xFF8B9198)
    val OutlineVariantDark = Color(0xFF41484D)
    val ScrimDark = Color(0xFF000000)
    val InverseSurfaceDark = Color(0xFFDFE3E7)
    val InverseOnSurfaceDark = Color(0xFF2C3135)
    val InversePrimaryDark = Color(0xFF206487)
    val SurfaceDimDark = Color(0xFF0F1417)
    val SurfaceBrightDark = Color(0xFF353A3D)
    val SurfaceContainerLowestDark = Color(0xFF0A0F12)
    val SurfaceContainerLowDark = Color(0xFF181C1F)
    val SurfaceContainerDark = Color(0xFF1C2024)
    val SurfaceContainerHighDark = Color(0xFF262A2E)
    val SurfaceContainerHighestDark = Color(0xFF313539)
}
