package theme.color

import androidx.compose.ui.graphics.Color

object You {
    val PrimaryLight = Color(0xFF28638A)
    val OnPrimaryLight = Color(0xFFFFFFFF)
    val PrimaryContainerLight = Color(0xFFCAE6FF)
    val OnPrimaryContainerLight = Color(0xFF001E30)
    val SecondaryLight = Color(0xFF50606F)
    val OnSecondaryLight = Color(0xFFFFFFFF)
    val SecondaryContainerLight = Color(0xFFD3E5F6)
    val OnSecondaryContainerLight = Color(0xFF0C1D29)
    val TertiaryLight = Color(0xFF65587B)
    val OnTertiaryLight = Color(0xFFFFFFFF)
    val TertiaryContainerLight = Color(0xFFEBDCFF)
    val OnTertiaryContainerLight = Color(0xFF201634)
    val ErrorLight = Color(0xFFBA1A1A)
    val OnErrorLight = Color(0xFFFFFFFF)
    val ErrorContainerLight = Color(0xFFFFDAD6)
    val OnErrorContainerLight = Color(0xFF410002)
    val BackgroundLight = Color(0xFFF7F9FF)
    val OnBackgroundLight = Color(0xFF181C20)
    val SurfaceLight = Color(0xFFF7F9FF)
    val OnSurfaceLight = Color(0xFF181C20)
    val SurfaceVariantLight = Color(0xFFDDE3EA)
    val OnSurfaceVariantLight = Color(0xFF41474D)
    val OutlineLight = Color(0xFF72787E)
    val OutlineVariantLight = Color(0xFFC1C7CE)
    val ScrimLight = Color(0xFF000000)
    val InverseSurfaceLight = Color(0xFF2D3135)
    val InverseOnSurfaceLight = Color(0xFFEEF1F6)
    val InversePrimaryLight = Color(0xFF96CCF8)
    val SurfaceDimLight = Color(0xFFD7DADF)
    val SurfaceBrightLight = Color(0xFFF7F9FF)
    val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
    val SurfaceContainerLowLight = Color(0xFFF1F4F9)
    val SurfaceContainerLight = Color(0xFFEBEEF3)
    val SurfaceContainerHighLight = Color(0xFFE5E8ED)
    val SurfaceContainerHighestLight = Color(0xFFE0E3E8)

    val PrimaryDark = Color(0xFF96CCF8)
    val OnPrimaryDark = Color(0xFF00344F)
    val PrimaryContainerDark = Color(0xFF004B70)
    val OnPrimaryContainerDark = Color(0xFFCAE6FF)
    val SecondaryDark = Color(0xFFB7C9D9)
    val OnSecondaryDark = Color(0xFF22323F)
    val SecondaryContainerDark = Color(0xFF384956)
    val OnSecondaryContainerDark = Color(0xFFD3E5F6)
    val TertiaryDark = Color(0xFFD0C0E8)
    val OnTertiaryDark = Color(0xFF362B4A)
    val TertiaryContainerDark = Color(0xFF4D4162)
    val OnTertiaryContainerDark = Color(0xFFEBDCFF)
    val ErrorDark = Color(0xFFFFB4AB)
    val OnErrorDark = Color(0xFF690005)
    val ErrorContainerDark = Color(0xFF93000A)
    val OnErrorContainerDark = Color(0xFFFFDAD6)
    val BackgroundDark = Color(0xFF101417)
    val OnBackgroundDark = Color(0xFFE0E3E8)
    val SurfaceDark = Color(0xFF101417)
    val OnSurfaceDark = Color(0xFFE0E3E8)
    val SurfaceVariantDark = Color(0xFF41474D)
    val OnSurfaceVariantDark = Color(0xFFC1C7CE)
    val OutlineDark = Color(0xFF8B9198)
    val OutlineVariantDark = Color(0xFF41474D)
    val ScrimDark = Color(0xFF000000)
    val InverseSurfaceDark = Color(0xFFE0E3E8)
    val InverseOnSurfaceDark = Color(0xFF2D3135)
    val InversePrimaryDark = Color(0xFF28638A)
    val SurfaceDimDark = Color(0xFF101417)
    val SurfaceBrightDark = Color(0xFF363A3E)
    val SurfaceContainerLowestDark = Color(0xFF0B0F12)
    val SurfaceContainerLowDark = Color(0xFF181C20)
    val SurfaceContainerDark = Color(0xFF1C2024)
    val SurfaceContainerHighDark = Color(0xFF262A2E)
    val SurfaceContainerHighestDark = Color(0xFF313539)
}
