package theme.color

import androidx.compose.ui.graphics.Color

object Yu {
    val PrimaryLight = Color(0xFF070808)
    val OnPrimaryLight = Color(0xFFFFFFFF)
    val PrimaryContainerLight = Color(0xFF2A2A2A)
    val OnPrimaryContainerLight = Color(0xFFB8B6B5)
    val SecondaryLight = Color(0xFF5F5E5E)
    val OnSecondaryLight = Color(0xFFFFFFFF)
    val SecondaryContainerLight = Color(0xFFE9E6E5)
    val OnSecondaryContainerLight = Color(0xFF4B4A4A)
    val TertiaryLight = Color(0xFF080808)
    val OnTertiaryLight = Color(0xFFFFFFFF)
    val TertiaryContainerLight = Color(0xFF2B2A2A)
    val OnTertiaryContainerLight = Color(0xFFB9B6B5)
    val ErrorLight = Color(0xFFBA1A1A)
    val OnErrorLight = Color(0xFFFFFFFF)
    val ErrorContainerLight = Color(0xFFFFDAD6)
    val OnErrorContainerLight = Color(0xFF410002)
    val BackgroundLight = Color(0xFFFDF8F8)
    val OnBackgroundLight = Color(0xFF1C1B1B)
    val SurfaceLight = Color(0xFFFDF8F8)
    val OnSurfaceLight = Color(0xFF1C1B1B)
    val SurfaceVariantLight = Color(0xFFE0E3E3)
    val OnSurfaceVariantLight = Color(0xFF444748)
    val OutlineLight = Color(0xFF747878)
    val OutlineVariantLight = Color(0xFFC4C7C7)
    val ScrimLight = Color(0xFF000000)
    val InverseSurfaceLight = Color(0xFF313030)
    val InverseOnSurfaceLight = Color(0xFFF4F0EF)
    val InversePrimaryLight = Color(0xFFC8C6C5)
    val SurfaceDimLight = Color(0xFFDDD9D8)
    val SurfaceBrightLight = Color(0xFFFDF8F8)
    val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
    val SurfaceContainerLowLight = Color(0xFFF7F3F2)
    val SurfaceContainerLight = Color(0xFFF1EDEC)
    val SurfaceContainerHighLight = Color(0xFFEBE7E6)
    val SurfaceContainerHighestLight = Color(0xFFE5E2E1)

    val PrimaryDark = Color(0xFFC8C6C5)
    val OnPrimaryDark = Color(0xFF303030)
    val PrimaryContainerDark = Color(0xFF161616)
    val OnPrimaryContainerDark = Color(0xFFA4A2A1)
    val SecondaryDark = Color(0xFFC9C6C5)
    val OnSecondaryDark = Color(0xFF313030)
    val SecondaryContainerDark = Color(0xFF3E3D3D)
    val OnSecondaryContainerDark = Color(0xFFD3D0CF)
    val TertiaryDark = Color(0xFFC9C6C5)
    val OnTertiaryDark = Color(0xFF313030)
    val TertiaryContainerDark = Color(0xFF171616)
    val OnTertiaryContainerDark = Color(0xFFA5A2A1)
    val ErrorDark = Color(0xFFFFB4AB)
    val OnErrorDark = Color(0xFF690005)
    val ErrorContainerDark = Color(0xFF93000A)
    val OnErrorContainerDark = Color(0xFFFFDAD6)
    val BackgroundDark = Color(0xFF141313)
    val OnBackgroundDark = Color(0xFFE5E2E1)
    val SurfaceDark = Color(0xFF141313)
    val OnSurfaceDark = Color(0xFFE5E2E1)
    val SurfaceVariantDark = Color(0xFF444748)
    val OnSurfaceVariantDark = Color(0xFFC4C7C7)
    val OutlineDark = Color(0xFF8E9192)
    val OutlineVariantDark = Color(0xFF444748)
    val ScrimDark = Color(0xFF000000)
    val InverseSurfaceDark = Color(0xFFE5E2E1)
    val InverseOnSurfaceDark = Color(0xFF313030)
    val InversePrimaryDark = Color(0xFF5F5E5E)
    val SurfaceDimDark = Color(0xFF141313)
    val SurfaceBrightDark = Color(0xFF3A3939)
    val SurfaceContainerLowestDark = Color(0xFF0E0E0E)
    val SurfaceContainerLowDark = Color(0xFF1C1B1B)
    val SurfaceContainerDark = Color(0xFF201F1F)
    val SurfaceContainerHighDark = Color(0xFF2B2A2A)
    val SurfaceContainerHighestDark = Color(0xFF353434)
}
