package theme.color

import androidx.compose.ui.graphics.Color

object Yuika {
    val PrimaryLight = Color(0xFF256489)
    val OnPrimaryLight = Color(0xFFFFFFFF)
    val PrimaryContainerLight = Color(0xFFC9E6FF)
    val OnPrimaryContainerLight = Color(0xFF001E2F)
    val SecondaryLight = Color(0xFF4F606E)
    val OnSecondaryLight = Color(0xFFFFFFFF)
    val SecondaryContainerLight = Color(0xFFD3E5F5)
    val OnSecondaryContainerLight = Color(0xFF0B1D29)
    val TertiaryLight = Color(0xFF64597C)
    val OnTertiaryLight = Color(0xFFFFFFFF)
    val TertiaryContainerLight = Color(0xFFEADDFF)
    val OnTertiaryContainerLight = Color(0xFF1F1635)
    val ErrorLight = Color(0xFFBA1A1A)
    val OnErrorLight = Color(0xFFFFFFFF)
    val ErrorContainerLight = Color(0xFFFFDAD6)
    val OnErrorContainerLight = Color(0xFF410002)
    val BackgroundLight = Color(0xFFF7F9FE)
    val OnBackgroundLight = Color(0xFF181C20)
    val SurfaceLight = Color(0xFFF7F9FE)
    val OnSurfaceLight = Color(0xFF181C20)
    val SurfaceVariantLight = Color(0xFFDDE3EA)
    val OnSurfaceVariantLight = Color(0xFF41474D)
    val OutlineLight = Color(0xFF71787E)
    val OutlineVariantLight = Color(0xFFC1C7CE)
    val ScrimLight = Color(0xFF000000)
    val InverseSurfaceLight = Color(0xFF2D3135)
    val InverseOnSurfaceLight = Color(0xFFEEF1F6)
    val InversePrimaryLight = Color(0xFF94CDF7)
    val SurfaceDimLight = Color(0xFFD7DADF)
    val SurfaceBrightLight = Color(0xFFF7F9FE)
    val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
    val SurfaceContainerLowLight = Color(0xFFF1F4F9)
    val SurfaceContainerLight = Color(0xFFEBEEF3)
    val SurfaceContainerHighLight = Color(0xFFE5E8ED)
    val SurfaceContainerHighestLight = Color(0xFFDFE3E8)

    val PrimaryDark = Color(0xFF94CDF7)
    val OnPrimaryDark = Color(0xFF00344D)
    val PrimaryContainerDark = Color(0xFF004C6E)
    val OnPrimaryContainerDark = Color(0xFFC9E6FF)
    val SecondaryDark = Color(0xFFB7C9D9)
    val OnSecondaryDark = Color(0xFF21323F)
    val SecondaryContainerDark = Color(0xFF384956)
    val OnSecondaryContainerDark = Color(0xFFD3E5F5)
    val TertiaryDark = Color(0xFFCEC0E8)
    val OnTertiaryDark = Color(0xFF352B4B)
    val TertiaryContainerDark = Color(0xFF4C4163)
    val OnTertiaryContainerDark = Color(0xFFEADDFF)
    val ErrorDark = Color(0xFFFFB4AB)
    val OnErrorDark = Color(0xFF690005)
    val ErrorContainerDark = Color(0xFF93000A)
    val OnErrorContainerDark = Color(0xFFFFDAD6)
    val BackgroundDark = Color(0xFF101417)
    val OnBackgroundDark = Color(0xFFDFE3E8)
    val SurfaceDark = Color(0xFF101417)
    val OnSurfaceDark = Color(0xFFDFE3E8)
    val SurfaceVariantDark = Color(0xFF41474D)
    val OnSurfaceVariantDark = Color(0xFFC1C7CE)
    val OutlineDark = Color(0xFF8B9198)
    val OutlineVariantDark = Color(0xFF41474D)
    val ScrimDark = Color(0xFF000000)
    val InverseSurfaceDark = Color(0xFFDFE3E8)
    val InverseOnSurfaceDark = Color(0xFF2D3135)
    val InversePrimaryDark = Color(0xFF256489)
    val SurfaceDimDark = Color(0xFF101417)
    val SurfaceBrightDark = Color(0xFF353A3E)
    val SurfaceContainerLowestDark = Color(0xFF0A0F12)
    val SurfaceContainerLowDark = Color(0xFF181C20)
    val SurfaceContainerDark = Color(0xFF1C2024)
    val SurfaceContainerHighDark = Color(0xFF262A2E)
    val SurfaceContainerHighestDark = Color(0xFF313539)
}
